/* =========================================================================
   ヨセミテ英語クエスト ― 語彙データ
   出典/題材: NPS Yosemite (nps.gov/yose) の nature / historyculture / animals 等
   { s:英文(*で囲った語=下線), m:正解の意味, kana:発音,
     cat: geo=地形/地質 spot=名所/景観 hist=歴史/人物 nat=自然(動植物/生態),
     lv: 1=英検2級 2=準1級 3=1級・専門, d:[近い誤答...], note:一言 }
   ルール: 選択肢(m/d)にラテン文字・対象語のカタカナ読みを入れない
   ========================================================================= */
window.QUIZ_DATA = [

/* ===================== geo：地形・地質 ===================== */
 {s:"Yosemite Valley was *sculpted* by ancient glaciers.", m:"（彫るように）形づくられた", kana:"スカルプテッド", cat:"geo", lv:2, note:"sculpt=彫刻する", d:["崩れ落ちた","埋め立てられた","水没した"]},
 {s:"El Capitan is a massive granite *monolith*.", m:"一枚岩・巨大な岩塊", kana:"モノリス", cat:"geo", lv:2, note:"mono(一)+lith(石)", d:["洞窟","石碑","峰の連なり"]},
 {s:"The walls of El Capitan are almost perfectly *sheer*.", m:"（切り立って）垂直な", kana:"シアー", cat:"geo", lv:2, note:"sheer cliff=絶壁", d:["なだらかな","ぎざぎざの","ひび割れた"]},
 {s:"Half Dome is the park's most famous granite *dome*.", m:"半球状の岩山", kana:"ドーム", cat:"geo", lv:1, d:["尖った峰","洞窟","深い割れ目"]},
 {s:"Bridalveil Fall drops from a *hanging* valley.", m:"（本谷の上に）宙づりに残った", kana:"ハンギング", cat:"geo", lv:3, note:"hanging valley=懸谷", d:["崩れかけた","水をたたえた","広く開けた"]},
 {s:"The high peaks rise as sharp granite *spires*.", m:"尖塔状の峰", kana:"スパイアズ", cat:"geo", lv:2, note:"spire=尖塔", d:["丸い丘","平らな台地","岩の裂け目"]},
 {s:"Most of the park sits on solid granite *bedrock*.", m:"岩盤・基盤の岩", kana:"ベッドロック", cat:"geo", lv:2, d:["表土","砂利層","粘土層"]},
 {s:"The range was slowly *uplifted* along a fault.", m:"隆起した・持ち上げられた", kana:"アップリフテッド", cat:"geo", lv:2, note:"uplift=隆起", d:["沈降した","水平に伸びた","削り取られた"]},
 {s:"Over millions of years, *erosion* wore the rock down.", m:"侵食", kana:"イロージョン", cat:"geo", lv:1, d:["堆積","噴火","風化を防ぐこと"]},
 {s:"Passing glaciers left the granite smooth and *polished*.", m:"磨かれた", kana:"ポリッシュト", cat:"geo", lv:1, d:["ひび割れた","黒ずんだ","苔むした"]},
 {s:"A lone boulder left by ice is called an *erratic*.", m:"迷子石（氷河が運んだ孤立した岩）", kana:"エラティック", cat:"geo", lv:3, note:"erratic=迷子石", d:["落石","石積みの道標","柱状節理の岩"]},
 {s:"Ridges of rock left by a glacier form a *moraine*.", m:"氷河が積んだ土砂の丘（堆石）", kana:"モレーン", cat:"geo", lv:3, note:"moraine=氷堆石", d:["砂丘","溶岩流","三角州"]},
 {s:"*Rockfall* is the most active force shaping the valley today.", m:"落石・岩盤崩落", kana:"ロックフォール", cat:"geo", lv:2, note:"NPS:現在最も活発な地質作用", d:["地滑り","鉄砲水","地震"]},
 {s:"These granites are part of the Sierra Nevada *batholith*.", m:"底盤（巨大な花崗岩体）", kana:"バソリス", cat:"geo", lv:3, note:"batholith=底盤", d:["断層帯","火口","鉱脈"]},
 {s:"The granite formed as *magma* slowly cooled underground.", m:"地下の溶けた岩", kana:"マグマ", cat:"geo", lv:1, d:["溶岩流","地下水","堆積物"]},
 {s:"Half Dome and El Capitan are truly *iconic* landmarks.", m:"象徴的な・誰もが知る", kana:"アイコニック", cat:"geo", lv:1, d:["ありふれた","神聖な","伝説上の"]},
 {s:"Streams from side canyons *plunge* into the main valley.", m:"（滝のように）落ち込む", kana:"プランジ", cat:"geo", lv:2, note:"plunge=急落する", d:["合流する","蛇行する","涸れる"]},
 {s:"Yosemite's granite peaks look *rugged* and wild.", m:"ごつごつした・荒々しい", kana:"ラゲッド", cat:"geo", lv:2, d:["なだらかな","湿った","色あせた"]},
 {s:"The glaciers *receded*, leaving lakes and meadows behind.", m:"後退した・引いた", kana:"リシーデッド", cat:"geo", lv:2, note:"recede=退く", d:["前進した","溶け合った","再び凍った"]},
 {s:"The Sierra Nevada is a tilted *fault-block* range.", m:"断層でできた地塊の（山地）", kana:"フォルトブロック", cat:"geo", lv:3, note:"断層block山地", d:["火山性の","堆積でできた","褶曲した"]},
 {s:"The mountains end abruptly in a steep *escarpment*.", m:"急崖・断層崖", kana:"エスカープメント", cat:"geo", lv:3, note:"escarpment=急斜面の崖", d:["扇状地","なだらかな尾根","広い谷底"]},
 {s:"Mirror Lake is slowly filling with *sediment*.", m:"堆積物・土砂", kana:"セディメント", cat:"geo", lv:2, d:["雪解け水","水草","流氷"]},
 {s:"Cathedral Peak was *sharpened* by ice into a jagged spire.", m:"鋭くとがらされた", kana:"シャープンド", cat:"geo", lv:2, d:["丸くならされた","割り砕かれた","覆い隠された"]},
 {s:"Rockfalls can be *triggered* by rain or earthquakes.", m:"引き起こされる・誘発される", kana:"トリガード", cat:"geo", lv:2, note:"trigger=引き金を引く", d:["和らげられる","予知される","記録される"]},
 {s:"The Sierra crest tops 13,000 feet in *elevation*.", m:"標高", kana:"エレベーション", cat:"geo", lv:2, d:["気温","傾斜","面積"]},
 {s:"Yosemite preserves a *fascinating* geologic story.", m:"魅力的な・興味をそそる", kana:"ファシネイティング", cat:"geo", lv:1, d:["恐ろしい","単純な","ありふれた"]},
 {s:"Granite domes form as outer layers peel off in *exfoliation*.", m:"（岩の）剥離・玉ねぎ状のはがれ", kana:"エクスフォリエーション", cat:"geo", lv:3, note:"exfoliation joint", d:["風化のしみ","割れ目の充填","溶食"]},
 {s:"Freezing and thawing cause slow *weathering* of the rock.", m:"風化", kana:"ウェザリング", cat:"geo", lv:2, d:["侵食による運搬","堆積","隆起"]},
 {s:"Climbers wedge their fingers into a narrow *crevice*.", m:"岩の裂け目・すき間", kana:"クレヴィス", cat:"geo", lv:2, d:["岩棚","くぼみ","洞穴"]},
 {s:"The trail follows a narrow *ledge* along the cliff.", m:"岩棚・（崖の）棚状の出っ張り", kana:"レッジ", cat:"geo", lv:2, d:["裂け目","がれ場","谷底"]},
 {s:"A huge granite *slab* slid off the cliff face.", m:"一枚板状の岩", kana:"スラブ", cat:"geo", lv:2, d:["丸い巨礫","砂の層","岩の柱"]},
 {s:"Loose rock debris piles up as *talus* at the cliff base.", m:"崖錐（崖下の岩くずの斜面）", kana:"タラス", cat:"geo", lv:3, note:"talus/scree", d:["露頭","堆石","扇状地"]},
 {s:"Geologists study a rocky *outcrop* exposed on the ridge.", m:"露頭（地表に現れた岩）", kana:"アウトクロップ", cat:"geo", lv:3, d:["がけ崩れ跡","くぼ地","分水界"]},
 {s:"A slow-moving *glacier* once filled this whole valley.", m:"氷河", kana:"グレイシャー", cat:"geo", lv:1, d:["雪原","湖","溶岩流"]},
 {s:"The U-shaped profile is clearly *glacial* in origin.", m:"氷河による・氷河作用の", kana:"グレイシャル", cat:"geo", lv:2, d:["火山性の","河川による","風による"]},
 {s:"Ice *carved* the smooth walls of the canyon.", m:"削り取った・えぐった", kana:"カーヴド", cat:"geo", lv:1, d:["積み上げた","覆い隠した","磨き上げた"]},
 {s:"The Merced River runs through a deep *gorge*.", m:"（切り立った）峡谷", kana:"ゴージ", cat:"geo", lv:2, d:["扇状地","なだらかな谷","入り江"]},
 {s:"A steep *ravine* cuts down the mountainside.", m:"小峡谷・細い谷", kana:"ラヴィーン", cat:"geo", lv:3, d:["尾根","台地","河原"]},
 {s:"Between the cliffs opens a dark, narrow *chasm*.", m:"深い裂け目・断崖の割れ目", kana:"キャズム", cat:"geo", lv:3, d:["ゆるい斜面","広い草原","浅い窪地"]},
 {s:"Hikers keep back from the crumbling *precipice*.", m:"絶壁・断崖", kana:"プレシピス", cat:"geo", lv:3, d:["がれ場","尾根道","谷底"]},
 {s:"Cathedral Peak ends in a slender rock *pinnacle*.", m:"尖峰・とがった岩の頂", kana:"ピナクル", cat:"geo", lv:3, d:["丸い頂","広い肩","岩の裂け目"]},
 {s:"From the *summit*, the whole range spreads out below.", m:"頂上・山頂", kana:"サミット", cat:"geo", lv:1, d:["中腹","登山口","尾根の鞍部"]},
 {s:"The trail runs along a high, narrow *ridge*.", m:"尾根・稜線", kana:"リッジ", cat:"geo", lv:1, d:["谷底","崖のふち","岩棚"]},
 {s:"The rivers drain a vast mountain *basin*.", m:"盆地・（水を集める）流域", kana:"ベイスン", cat:"geo", lv:2, d:["尾根","滝つぼ","分水嶺"]},
 {s:"Ice scooped out a bowl-shaped *cirque* near the peak.", m:"圏谷（氷河が削った半円状のくぼ地）", kana:"サーク", cat:"geo", lv:3, note:"cirque=圏谷(カール)", d:["溶岩台地","崖錐","三日月湖"]},
 {s:"Above treeline, the *alpine* zone is bare rock and snow.", m:"高山の・高山帯の", kana:"アルパイン", cat:"geo", lv:2, d:["湿地帯の","森林の","砂漠の"]},
 {s:"Tuolumne Meadows lies in the cool *subalpine* zone.", m:"亜高山の", kana:"サブアルパイン", cat:"geo", lv:3, d:["高山帯上部の","低地の","海岸沿いの"]},
 {s:"Few trees grow above the *timberline*.", m:"森林限界", kana:"ティンバーライン", cat:"geo", lv:3, note:"treeline", d:["海抜ゼロ","雪線","分水界"]},
 {s:"A deep *snowpack* feeds the waterfalls each spring.", m:"積雪（層）", kana:"スノーパック", cat:"geo", lv:2, d:["氷河","地下水","霜柱"]},
 {s:"Steep slopes can release a deadly *avalanche*.", m:"雪崩", kana:"アヴァランチ", cat:"geo", lv:2, d:["土石流","落石","鉄砲水"]},
 {s:"Waterfalls swell with *meltwater* in late spring.", m:"雪解け水", kana:"メルトウォーター", cat:"geo", lv:2, d:["湧き水","雨水のたまり","地下水"]},
 {s:"Many small streams are *tributaries* of the Merced.", m:"支流", kana:"トリビュタリーズ", cat:"geo", lv:2, d:["本流","三日月湖","分水嶺"]},
 {s:"The two rivers meet at their *confluence*.", m:"合流点", kana:"コンフルエンス", cat:"geo", lv:3, d:["源流","河口","分岐"]},
 {s:"Snowmelt from the *watershed* fills the reservoir.", m:"分水界・（水を集める）流域", kana:"ウォーターシェッド", cat:"geo", lv:3, d:["用水路","堤防","河口の干潟"]},
 {s:"A giant granite *boulder* rests in the middle of the trail.", m:"巨礫・大きな丸石", kana:"ボルダー", cat:"geo", lv:1, d:["砂利","岩棚","石畳"]},
 {s:"Water seeps into every *fracture* in the rock.", m:"割れ目・断裂", kana:"フラクチャー", cat:"geo", lv:2, d:["表面のつや","層の境目","くぼみ"]},
 {s:"Yosemite's cliffs are made of pale *granite*.", m:"花崗岩", kana:"グラニット", cat:"geo", lv:1, d:["石灰岩","砂岩","玄武岩"]},
 {s:"The skyline is a row of *jagged* peaks.", m:"ぎざぎざの・のこぎり状の", kana:"ジャグド", cat:"geo", lv:2, d:["丸みを帯びた","なだらかな","平らな"]},
 {s:"An *overhanging* ledge shelters climbers from rain.", m:"（上に）せり出した", kana:"オーバーハンギング", cat:"geo", lv:2, d:["引っ込んだ","崩れかけた","水びたしの"]},
 {s:"Rushing meltwater *scours* the granite streambed.", m:"えぐる・洗い流して削る", kana:"スカウアーズ", cat:"geo", lv:3, note:"scour=洗掘", d:["埋め立てる","滑らかに磨く","堰き止める"]},
 {s:"Parallel *striations* show which way the ice moved.", m:"（氷河が刻んだ）擦り傷・条線", kana:"ストライエーションズ", cat:"geo", lv:3, d:["割れ目の網目","地層の縞","溶岩のしわ"]},
 {s:"By late summer the small falls may run dry as flows *dwindle*.", m:"次第に減る・細っていく", kana:"ドウィンドル", cat:"geo", lv:3, note:"dwindle=先細る", d:["急に増す","濁る","凍りつく"]},
 {s:"The stream is *swollen* with spring runoff.", m:"（水かさが）増した", kana:"スウォレン", cat:"geo", lv:2, d:["澄んだ","干上がった","よどんだ"]},
 {s:"Yosemite Falls is a spectacular *cascade* of white water.", m:"（段状に流れ落ちる）滝・奔流", kana:"カスケード", cat:"geo", lv:2, d:["よどみ","渦","水たまり"]},

/* ===================== spot：名所・景観・体験 ===================== */
 {s:"From Glacier Point you get a sweeping *vista* of the valley.", m:"（広がる）眺望・遠望", kana:"ビスタ", cat:"spot", lv:2, d:["近道","休憩所","案内板"]},
 {s:"Tunnel View is the valley's most famous *overlook*.", m:"見下ろす展望台", kana:"オーバールック", cat:"spot", lv:1, d:["登山口","広場","分岐点"]},
 {s:"Mariposa Grove protects hundreds of giant *sequoias*.", m:"北米原産の巨大な樹木", kana:"セコイアズ", cat:"spot", lv:1, note:"通称 Big Trees", d:["針葉樹の若木","樫の大木","洞窟群"]},
 {s:"The sequoias here are affectionately called the *Big Trees*.", m:"巨木の愛称・大木", kana:"ビッグツリーズ", cat:"spot", lv:1, d:["枯れた切り株","並木道","原生林全体"]},
 {s:"Tuolumne Meadows is a vast subalpine *meadow*.", m:"草原・草地", kana:"メドウ", cat:"spot", lv:1, d:["湿地","荒れ地","牧場の柵"]},
 {s:"Spray from the falls drenches hikers with cold *mist*.", m:"霧状のしぶき", kana:"ミスト", cat:"spot", lv:2, d:["虹","苔","急流"]},
 {s:"Inspiration Point offers a view of *stupendous* grandeur.", m:"途方もない・驚異的な", kana:"ステューペンダス", cat:"spot", lv:3, note:"NPS引用の語", d:["ささやかな","不気味な","荒涼とした"]},
 {s:"Early visitors stood *spellbound* at their first valley view.", m:"魅了されて・見とれて", kana:"スペルバウンド", cat:"spot", lv:3, note:"魔法にかかったよう", d:["おびえて","退屈して","当惑して"]},
 {s:"The valley's beauty fills visitors with *awe*.", m:"畏敬の念・感嘆", kana:"オー", cat:"spot", lv:2, d:["恐怖","退屈","懐かしさ"]},
 {s:"Glacier Point is a dramatic *vantage* point above the valley.", m:"見晴らしの利く観察地点", kana:"バンテージ", cat:"spot", lv:2, note:"vantage point", d:["野営適地","危険箇所","休憩場所"]},
 {s:"El Capitan's vertical *face* rises about 3,000 feet.", m:"（岩の）壁面", kana:"フェイス", cat:"spot", lv:2, note:"rock face=岩壁", d:["頂上","裾野","割れ目"]},
 {s:"The Ahwahnee Hotel is a *landmark* of rustic grand design.", m:"目印となる名所", kana:"ランドマーク", cat:"spot", lv:1, d:["廃墟","仮設小屋","展望塔"]},
 {s:"Tioga Road crosses the park's high-country *crest*.", m:"尾根・山の頂上線", kana:"クレスト", cat:"spot", lv:2, note:"crest=稜線", d:["谷底","麓","湖畔"]},
 {s:"The Ahwahnee's design blends into its *surroundings*.", m:"周囲の環境", kana:"サラウンディングス", cat:"spot", lv:1, d:["装飾","来客","歴史"]},
 {s:"Half Dome's cables make for a *strenuous* final climb.", m:"骨の折れる・きつい", kana:"ストレニュアス", cat:"spot", lv:2, d:["ゆるやかな","ごく短い","危険な"]},
 {s:"A short *spur* trail branches off to the viewpoint.", m:"（本道から分かれる）枝道", kana:"スパー", cat:"spot", lv:3, note:"spur trail=脇道", d:["近道","一方通行路","周回路"]},
 {s:"Half Dome rises high above Tenaya *Canyon*.", m:"峡谷", kana:"キャニオン", cat:"spot", lv:1, d:["尾根","草原","湖沼"]},
 {s:"The scenery here is so grand it is often called *sublime*.", m:"崇高な・荘厳な", kana:"サブライム", cat:"spot", lv:3, note:"sublime=崇高", d:["快適な","素朴な","勇壮な"]},
 {s:"Bridalveil Fall sways in the *breeze* like a thin veil.", m:"そよ風", kana:"ブリーズ", cat:"spot", lv:1, d:["水しぶき","朝もや","日差し"]},
 {s:"From the ridge opens a full *panorama* of the high country.", m:"全景・見渡すかぎりの眺め", kana:"パノラマ", cat:"spot", lv:2, d:["接写","一区画","立ち入り禁止区域"]},
 {s:"A marked *viewpoint* looks straight across at Half Dome.", m:"展望地点", kana:"ビューポイント", cat:"spot", lv:1, d:["野営地","分水界","給水所"]},
 {s:"The trail climbs the slope in tight *switchbacks*.", m:"つづら折り（の道）", kana:"スイッチバックス", cat:"spot", lv:2, note:"九十九折り", d:["石段","直登の道","下り坂"]},
 {s:"A wooden *boardwalk* protects the fragile meadow.", m:"木道・板張りの遊歩道", kana:"ボードウォーク", cat:"spot", lv:2, d:["石垣","丸太橋","展望デッキ"]},
 {s:"Cross the creek on a small *footbridge*.", m:"歩行者用の橋", kana:"フットブリッジ", cat:"spot", lv:1, d:["飛び石","桟橋","堰"]},
 {s:"Stacked stones called a *cairn* mark the faint route.", m:"石積みの道標", kana:"ケアン", cat:"spot", lv:3, note:"cairn=ケルン", d:["里程標","案内看板","境界石"]},
 {s:"Most of Yosemite is protected as *wilderness*.", m:"手つかずの原生自然", kana:"ウィルダネス", cat:"spot", lv:2, note:"NPS:約95%が指定", d:["観光地区","牧草地","保養地"]},
 {s:"Permits are required to camp in the *backcountry*.", m:"（道の奥の）山奥・奥地", kana:"バックカントリー", cat:"spot", lv:2, d:["駐車場周辺","谷の中心部","入口ゲート"]},
 {s:"The valley *campground* fills up months in advance.", m:"野営場", kana:"キャンプグラウンド", cat:"spot", lv:1, d:["展望台","休憩所","案内所"]},
 {s:"A cozy *lodge* offers rooms near the valley floor.", m:"山の宿・宿泊小屋", kana:"ロッジ", cat:"spot", lv:1, d:["炊事場","避難壕","見張り小屋"]},
 {s:"A quiet *grove* of sequoias stands beside the trail.", m:"木立・小さな林", kana:"グローブ", cat:"spot", lv:2, d:["草地","湿原","荒れ地"]},
 {s:"On Half Dome, steel *cables* help hikers up the last pitch.", m:"（登行補助の）鎖・ケーブル", kana:"ケーブルズ", cat:"spot", lv:1, d:["手すり","はしご","ロープの結び目"]},
 {s:"You need a *permit* to hike Half Dome.", m:"許可証", kana:"パーミット", cat:"spot", lv:1, d:["予約金","会員証","入場整理券"]},
 {s:"Ask questions at the *ranger station*.", m:"公園管理事務所", kana:"レンジャーステーション", cat:"spot", lv:1, d:["売店","診療所","宿泊棟"]},
 {s:"The views along Tioga Road are simply *scenic*.", m:"景色のよい・風光明媚な", kana:"シーニック", cat:"spot", lv:1, d:["殺風景な","険しい","にぎやかな"]},
 {s:"The first view of the valley is *breathtaking*.", m:"息をのむほど美しい", kana:"ブレステイキング", cat:"spot", lv:2, d:["がっかりする","目まぐるしい","ありふれた"]},
 {s:"Half Dome looks *majestic* in the evening light.", m:"荘厳な・雄大な", kana:"マジェスティック", cat:"spot", lv:2, d:["みすぼらしい","不気味な","こぢんまりした"]},
 {s:"At dawn the meadow feels calm and *serene*.", m:"澄んで静かな・のどかな", kana:"セリーン", cat:"spot", lv:2, d:["騒がしい","重苦しい","荒々しい"]},
 {s:"A *secluded* lake sits far from any road.", m:"人里離れた・ひっそりした", kana:"セクルーデッド", cat:"spot", lv:3, d:["混雑した","開けた","便利な"]},
 {s:"The high lakes remain clear and *pristine*.", m:"手つかずで清らかな", kana:"プリスティーン", cat:"spot", lv:3, d:["濁った","荒れ果てた","人工の"]},
 {s:"A steep *ascent* leads to Glacier Point.", m:"登り・上り坂", kana:"アセント", cat:"spot", lv:2, d:["下り","平坦路","回り道"]},
 {s:"The *descent* back to the valley is hard on the knees.", m:"下り・下降", kana:"ディセント", cat:"spot", lv:2, d:["登り","休息","近道"]},
 {s:"A short *detour* avoids the flooded section of trail.", m:"迂回路・回り道", kana:"ディツアー", cat:"spot", lv:2, d:["近道","分岐点","行き止まり"]},
 {s:"The Mist Trail is a popular *loop* past two waterfalls.", m:"周回（コース）", kana:"ループ", cat:"spot", lv:2, d:["直線の道","一方通行","下り専用路"]},
 {s:"The Arch Rock entrance is the valley's western *gateway*.", m:"玄関口・入口", kana:"ゲートウェイ", cat:"spot", lv:2, d:["中心広場","分水界","展望塔"]},
 {s:"The still lake gives a perfect *reflection* of Half Dome.", m:"（水面の）映り込み", kana:"リフレクション", cat:"spot", lv:1, d:["影絵","反響","かすみ"]},
 {s:"*Spray* from Vernal Fall soaks the granite steps.", m:"（飛び散る）水しぶき", kana:"スプレー", cat:"spot", lv:1, d:["こだま","露","泡"]},
 {s:"In afternoon light a *rainbow* arcs over the falls.", m:"虹", kana:"レインボー", cat:"spot", lv:1, d:["かすみ","日暈","稲妻"]},
 {s:"The falls are *thunderous* at peak snowmelt.", m:"雷のようにとどろく", kana:"サンダラス", cat:"spot", lv:2, d:["か細い","澄みきった","絶え間ない"]},
 {s:"The meadow is *lush* and green in early summer.", m:"青々と生い茂った", kana:"ラッシュ", cat:"spot", lv:2, d:["枯れた","乾ききった","刈られた"]},
 {s:"Half Dome makes a *picturesque* subject for photos.", m:"絵のように美しい", kana:"ピクチャレスク", cat:"spot", lv:3, d:["味気ない","ゆがんだ","雄々しい"]},
 {s:"An *interpretive* sign explains how the valley formed.", m:"（来園者向けに）解説する", kana:"インタープリティブ", cat:"spot", lv:3, note:"interpretive sign=解説板", d:["警告する","禁止する","宣伝する"]},
 {s:"Pull over at the roadside *wayside* to read the exhibit.", m:"道端の展示・休憩スポット", kana:"ウェイサイド", cat:"spot", lv:3, d:["料金所","検問所","分岐点"]},

/* ===================== hist：歴史・人物・文化 ===================== */
 {s:"In 1864, Lincoln signed the *Yosemite Grant* to protect the land.", m:"1864年に谷を保護した法令", kana:"ヨセミテグラント", cat:"hist", lv:3, note:"自然保護の先駆けとなる法", d:["先住民との条約","国立公園法","土地払下げ令"]},
 {s:"John Muir was a *naturalist* who fought to protect Yosemite.", m:"博物学者・自然研究家", kana:"ナチュラリスト", cat:"hist", lv:1, d:["登山家","写真家","地質学者"]},
 {s:"Muir became a fierce *defender* of the wilderness.", m:"擁護者・守り手", kana:"ディフェンダー", cat:"hist", lv:1, d:["批評家","開拓者","案内人"]},
 {s:"The park's creation was an early act of *preservation*.", m:"（自然の）保存・保護", kana:"プリザベーション", cat:"hist", lv:2, note:"preserve=保存する", d:["開発","調査","復元"]},
 {s:"Conservationists still promote careful *stewardship* of the land.", m:"（引き継ぎ守る）責任ある管理", kana:"スチュワードシップ", cat:"hist", lv:3, note:"stewardship", d:["所有権","搾取","観光開発"]},
 {s:"The Ahwahneechee are the valley's *ancestral* people.", m:"先祖代々の・祖先の", kana:"アンセストラル", cat:"hist", lv:2, note:"ancestral homeland", d:["移住してきた","近隣の","伝説上の"]},
 {s:"Their *descendants* remain part of Yosemite today.", m:"子孫", kana:"ディセンダンツ", cat:"hist", lv:2, d:["祖先","親族","移民"]},
 {s:"For the Ahwahneechee, the valley was their *homeland*.", m:"故郷・本拠地", kana:"ホームランド", cat:"hist", lv:1, d:["狩り場","聖地","避難地"]},
 {s:"The Gold Rush brought new *settlers* into the Sierra.", m:"入植者・移住者", kana:"セトラーズ", cat:"hist", lv:1, d:["観光客","兵士","行商人"]},
 {s:"Pioneers ran *stagecoach* lines to the distant valley.", m:"駅馬車", kana:"ステージコーチ", cat:"hist", lv:3, note:"昔の乗合馬車", d:["蒸気機関車","荷馬","渡し船"]},
 {s:"Galen Clark served as the *guardian* of the Yosemite Grant.", m:"管理人・守護者", kana:"ガーディアン", cat:"hist", lv:2, d:["測量士","初代所長","案内人"]},
 {s:"Word of the valley's *grandeur* spread around the world.", m:"雄大さ・壮麗さ", kana:"グランジャー", cat:"hist", lv:2, note:"grand=壮大な", d:["静けさ","険しさ","神秘さ"]},
 {s:"Ansel Adams was a *renowned* photographer of Yosemite.", m:"高名な・名高い", kana:"リナウンド", cat:"hist", lv:2, d:["無名の","風変わりな","地元出身の"]},
 {s:"Illustrators and writers helped *publicize* the valley.", m:"世に広める・宣伝する", kana:"パブリサイズ", cat:"hist", lv:2, note:"publicize", d:["保護する","測量する","開発する"]},
 {s:"The Mariposa Battalion was an armed *militia*.", m:"民兵（隊）", kana:"ミリシャ", cat:"hist", lv:3, note:"militia=民兵組織", d:["正規軍","探検隊","自警の商人団"]},
 {s:"Buffalo Soldiers were among the first park *rangers*.", m:"公園管理官・監視員", kana:"レンジャーズ", cat:"hist", lv:1, d:["案内係の住民","開拓者","測量隊"]},
 {s:"The Ahwahneechee faced *forcible* removal from the valley.", m:"力ずくの・強制的な", kana:"フォーシブル", cat:"hist", lv:3, note:"forcible=強制の", d:["自発的な","段階的な","一時的な"]},
 {s:"Their contributions left a lasting *legacy*.", m:"遺産・受け継がれるもの", kana:"レガシー", cat:"hist", lv:2, d:["負担","記録","名声"]},
 {s:"People have lived here since *time immemorial*.", m:"大昔から・有史以前から", kana:"タイムイミモリアル", cat:"hist", lv:3, note:"太古の昔から", d:["建国以来","氷河期の直後から","ここ数世紀"]},
 {s:"Once open to settlement, the land drew *speculation*.", m:"（土地の）投機・思惑買い", kana:"スペキュレーション", cat:"hist", lv:3, note:"speculation=投機", d:["移民の波","観光客","課税"]},
 {s:"The Gold Rush sparked *conflict* over land and resources.", m:"対立・争い", kana:"コンフリクト", cat:"hist", lv:1, d:["交易","協力","契約"]},
 {s:"Muir's writings inspired a movement for *conservation*.", m:"（自然）保護・保全", kana:"コンサベーション", cat:"hist", lv:2, note:"conservation", d:["開拓","観光振興","学術研究"]},
 {s:"Early tourism made Yosemite a *world-class* destination.", m:"世界屈指の", kana:"ワールドクラス", cat:"hist", lv:2, d:["地方限定の","秘境の","高級志向の"]},
 {s:"John Muir first *measured* a glacier's movement in 1872.", m:"測定した", kana:"メジャード", cat:"hist", lv:1, d:["発見した","描いた","命名した"]},
 {s:"In 1890, Congress voted to *establish* Yosemite National Park.", m:"設立する・制定する", kana:"エスタブリッシュ", cat:"hist", lv:2, d:["拡張する","廃止する","移転する"]},
 {s:"The 1864 grant *designated* the valley for public use.", m:"（正式に）指定した", kana:"デジグネイテッド", cat:"hist", lv:2, note:"designate=指定する", d:["売却した","測量した","放棄した"]},
 {s:"Muir was a tireless *advocate* for the national parks.", m:"擁護者・主唱者", kana:"アドヴォケイト", cat:"hist", lv:2, d:["反対者","傍観者","出資者"]},
 {s:"Conservation *activists* lobbied Congress for the park.", m:"活動家", kana:"アクティビスツ", cat:"hist", lv:2, d:["役人","出資者","報道記者"]},
 {s:"Supporters sent a *petition* to protect the sequoias.", m:"請願（書）", kana:"ペティション", cat:"hist", lv:2, d:["寄付金","抗議行進","報告書"]},
 {s:"The Ahwahneechee are *indigenous* to this valley.", m:"先住の・その土地固有の", kana:"インディジナス", cat:"hist", lv:2, d:["移民の","入植した","放浪の"]},
 {s:"Basket weaving is part of the tribe's living *heritage*.", m:"（受け継がれた）遺産・伝統", kana:"ヘリテージ", cat:"hist", lv:2, d:["財産","負債","名声"]},
 {s:"Settlement led to the *displacement* of native families.", m:"立ち退き・追い立て", kana:"ディスプレイスメント", cat:"hist", lv:3, note:"displace=移動させる", d:["定住","同化","移民の受け入れ"]},
 {s:"Miners and *prospectors* poured into the foothills.", m:"（鉱脈を探す）探鉱者・山師", kana:"プロスペクターズ", cat:"hist", lv:3, d:["行商人","測量士","牧夫"]},
 {s:"A park *superintendent* oversees daily operations.", m:"（公園の）管理責任者・園長", kana:"スーパーインテンデント", cat:"hist", lv:3, d:["案内係","出資者","森林警備員"]},
 {s:"Mounted *cavalry* patrolled the early park.", m:"騎兵（隊）", kana:"キャバルリー", cat:"hist", lv:3, note:"buffalo soldiers", d:["歩兵","民兵","測量隊"]},
 {s:"Growing *tourism* reshaped the valley in the late 1800s.", m:"観光（業）", kana:"ツーリズム", cat:"hist", lv:1, d:["鉱業","農業","林業"]},
 {s:"Surveyors marked the park's new *boundary*.", m:"境界（線）", kana:"バウンダリー", cat:"hist", lv:2, d:["中心","面積","標高"]},
 {s:"Crews were sent to *survey* and map the region.", m:"測量する・調査する", kana:"サーヴェイ", cat:"hist", lv:2, d:["開墾する","保護する","放牧する"]},
 {s:"Muir helped *found* the Sierra Club in 1892.", m:"創設する・設立する", kana:"ファウンド", cat:"hist", lv:2, note:"found=創設する", d:["解散させる","率いる","脱退する"]},
 {s:"The park was later *expanded* to protect more land.", m:"拡張された", kana:"エクスパンデッド", cat:"hist", lv:2, d:["縮小された","分割された","閉鎖された"]},
 {s:"Yosemite was *proclaimed* a place worth saving.", m:"（公に）宣言された", kana:"プロクレイムド", cat:"hist", lv:3, note:"proclaim=布告する", d:["否定された","課税された","競売された"]},
 {s:"Muir's books *inspired* generations of park visitors.", m:"奮い立たせた・触発した", kana:"インスパイアード", cat:"hist", lv:1, d:["失望させた","当惑させた","退屈させた"]},
 {s:"Photographers helped *document* the vanishing wilderness.", m:"記録する", kana:"ドキュメント", cat:"hist", lv:2, d:["誇張する","破壊する","独占する"]},
 {s:"Early writers *chronicled* the valley's discovery.", m:"（時系列で）記録した", kana:"クロニクルド", cat:"hist", lv:3, note:"chronicle=年代記に記す", d:["否定した","誇張した","翻訳した"]},
 {s:"Yosemite was named a World Heritage *Site* in 1984.", m:"（重要な）場所・遺産地", kana:"サイト", cat:"hist", lv:2, note:"World Heritage Site", d:["候補","団体","記念日"]},
 {s:"The valley became a *sanctuary* for wildlife and people alike.", m:"保護区・安息の地", kana:"サンクチュアリ", cat:"hist", lv:3, d:["交易所","狩猟場","開拓地"]},
 {s:"Muir urged the nation to *cherish* its wild places.", m:"大切にする・慈しむ", kana:"チェリッシュ", cat:"hist", lv:2, d:["見放す","切り開く","支配する"]},

/* ===================== nat：自然（動植物・生態） ===================== */
 {s:"*Conifers* such as pine and fir cover the slopes.", m:"針葉樹", kana:"コニファーズ", cat:"nat", lv:2, d:["広葉樹","つる植物","地衣類"]},
 {s:"The pale bark of a *ponderosa pine* smells of vanilla.", m:"背の高い松の一種", kana:"ポンデローサパイン", cat:"nat", lv:3, d:["低いかん木","つる草","シダ植物"]},
 {s:"*Incense cedar* has soft, fragrant foliage.", m:"ヒノキ科の常緑高木", kana:"インセンスシダー", cat:"nat", lv:3, d:["落葉するかん木","高山の草","水辺の葦"]},
 {s:"California *black oak* drops acorns each autumn.", m:"カシ・ナラの一種", kana:"ブラックオーク", cat:"nat", lv:2, d:["針葉樹","つる植物","低木のヤシ"]},
 {s:"Dense *chaparral* covers the dry foothills.", m:"乾いた土地の低木のやぶ", kana:"チャパラル", cat:"nat", lv:3, note:"NPSの植生用語", d:["湿地の草原","高山の裸地","針葉樹林"]},
 {s:"Sunlight filters through the forest *canopy*.", m:"樹冠・林の上層", kana:"キャノピー", cat:"nat", lv:2, d:["林床","根の張り","下草"]},
 {s:"Shade plants grow in the forest *understory*.", m:"林床の低木・下層", kana:"アンダーストーリー", cat:"nat", lv:3, d:["樹冠","梢","幹の表皮"]},
 {s:"A woodpecker drills into the tree's *bark*.", m:"樹皮", kana:"バーク", cat:"nat", lv:1, d:["樹液","若芽","年輪"]},
 {s:"Sticky *sap* oozes from the pine's wound.", m:"樹液", kana:"サップ", cat:"nat", lv:2, d:["花粉","蜜ろう","樹皮"]},
 {s:"Each sequoia *cone* holds hundreds of tiny seeds.", m:"球果・松ぼっくり", kana:"コーン", cat:"nat", lv:2, d:["新芽","葉のふさ","樹皮片"]},
 {s:"Fire helps sequoia seeds *germinate*.", m:"発芽する", kana:"ジャーミネイト", cat:"nat", lv:3, note:"germinate=発芽", d:["枯れる","開花する","結実する"]},
 {s:"Bees *pollinate* the meadow's wildflowers.", m:"受粉させる", kana:"ポリネイト", cat:"nat", lv:2, d:["食い荒らす","種をまく","刈り取る"]},
 {s:"Purple *lupine* blooms across the summer meadow.", m:"紫色の野草（マメ科）", kana:"ルーピン", cat:"nat", lv:3, d:["低木のやぶ","シダの群れ","高山の苔"]},
 {s:"Delicate *ferns* unfurl in the shady canyon.", m:"シダ（植物）", kana:"ファーンズ", cat:"nat", lv:1, d:["きのこ","つる草","若木"]},
 {s:"A *black bear* forages for berries in the forest.", m:"クロクマ", kana:"ブラックベア", cat:"nat", lv:1, note:"NPS:グリズリーは現在生息せず", d:["アライグマ","オオカミ","ヤマネコ"]},
 {s:"A *mule deer* freezes at the edge of the meadow.", m:"耳の大きなシカの一種", kana:"ミュールディア", cat:"nat", lv:2, d:["野ウサギ","カモシカ","子牛"]},
 {s:"A *coyote* trots across the snowy road.", m:"イヌ科の野生動物", kana:"コヨーテ", cat:"nat", lv:2, d:["キツネ","アナグマ","ヤマネコ"]},
 {s:"A shy *bobcat* hunts along the forest edge.", m:"尾の短い野生のネコ", kana:"ボブキャット", cat:"nat", lv:3, d:["カワウソ","テン","子グマ"]},
 {s:"A *marmot* suns itself on a granite slab.", m:"高山にすむリス科の動物", kana:"マーモット", cat:"nat", lv:3, d:["ハリネズミ","モグラ","カワネズミ"]},
 {s:"A tiny *pika* darts among the rocks.", m:"高山の岩場にすむ小動物（ナキウサギ）", kana:"ピカ", cat:"nat", lv:3, d:["トカゲ","小鳥","コウモリ"]},
 {s:"A *mountain lion* is rarely seen by visitors.", m:"ピューマ・大型のネコ科", kana:"マウンテンライオン", cat:"nat", lv:2, d:["野生の犬","大型のシカ","黒いクマ"]},
 {s:"Sierra Nevada *bighorn sheep* cling to steep cliffs.", m:"大きな角をもつ野生のヒツジ", kana:"ビッグホーンシープ", cat:"nat", lv:3, d:["野生のヤギ","カモシカ","大型のシカ"]},
 {s:"A bold *Steller's jay* raids the picnic table.", m:"青い羽の鳥（カケスの一種）", kana:"ステラーズジェイ", cat:"nat", lv:3, d:["小型のタカ","キツツキ","ハト"]},
 {s:"A *peregrine falcon* nests on the cliff face.", m:"ハヤブサ", kana:"ペレグリンファルコン", cat:"nat", lv:3, d:["ワシミミズク","ハクトウワシ","ノスリ"]},
 {s:"The rare *great gray owl* hunts in the meadows.", m:"大型のフクロウの一種", kana:"グレートグレイオウル", cat:"nat", lv:3, d:["タカの一種","夜行性のコウモリ","水鳥"]},
 {s:"Native *trout* live in the park's cold streams.", m:"マス（の仲間）", kana:"トラウト", cat:"nat", lv:2, d:["ナマズ","サケの稚魚","ウナギ"]},
 {s:"Frogs and salamanders are *amphibians*.", m:"両生類", kana:"アンフィビアンズ", cat:"nat", lv:2, d:["爬虫類","甲殻類","無脊椎動物"]},
 {s:"Lizards and snakes are *reptiles*.", m:"爬虫類", kana:"レプタイルズ", cat:"nat", lv:2, d:["両生類","哺乳類","軟体動物"]},
 {s:"Yosemite protects over 400 *vertebrate* species.", m:"脊椎動物（の）", kana:"バーテブレイト", cat:"nat", lv:3, note:"NPS:脊椎動物400種超", d:["無脊椎動物","外来種","絶滅種"]},
 {s:"Bears and deer are among the park's *mammals*.", m:"哺乳類", kana:"ママルズ", cat:"nat", lv:1, d:["鳥類","爬虫類","昆虫類"]},
 {s:"The coyote is a clever *predator*.", m:"捕食者", kana:"プレデター", cat:"nat", lv:2, d:["草食動物","獲物","腐肉食動物"]},
 {s:"Small rodents are common *prey* for hawks.", m:"獲物・餌食", kana:"プレイ", cat:"nat", lv:2, d:["天敵","仲間","巣"]},
 {s:"Bears *forage* for acorns, berries, and insects.", m:"（餌を）あさる・探し回る", kana:"フォリッジ", cat:"nat", lv:2, note:"NPS頻出語", d:["冬眠する","縄張りを守る","獲物を追う"]},
 {s:"Deer *graze* peacefully in the meadow.", m:"草を食む", kana:"グレイズ", cat:"nat", lv:2, d:["水を飲む","走り回る","身を隠す"]},
 {s:"Marmots *hibernate* through the long winter.", m:"冬眠する", kana:"ハイバネイト", cat:"nat", lv:2, d:["渡りをする","脱皮する","巣を作る"]},
 {s:"Some birds *migrate* south before the snow.", m:"渡る・移動する", kana:"マイグレイト", cat:"nat", lv:2, d:["冬眠する","群れる","巣ごもりする"]},
 {s:"Many small mammals are *nocturnal*.", m:"夜行性の", kana:"ノクターナル", cat:"nat", lv:3, d:["昼行性の","冬眠する","群れをなす"]},
 {s:"A fox rests in its underground *den*.", m:"（動物の）巣穴・ねぐら", kana:"デン", cat:"nat", lv:2, d:["水場","縄張り","餌場"]},
 {s:"Ground squirrels dig a deep *burrow*.", m:"（掘った）巣穴", kana:"バロウ", cat:"nat", lv:2, d:["木のうろ","岩の割れ目","鳥の巣"]},
 {s:"Each species needs the right *habitat* to survive.", m:"生息地", kana:"ハビタット", cat:"nat", lv:2, d:["食物連鎖","繁殖期","縄張り争い"]},
 {s:"Yosemite is rich in plant and animal *diversity*.", m:"多様性", kana:"ダイバーシティ", cat:"nat", lv:2, d:["密度","希少性","分布"]},
 {s:"Meadows and forests form a fragile *ecosystem*.", m:"生態系", kana:"エコシステム", cat:"nat", lv:2, d:["食物網","生息地","気候帯"]},
 {s:"Each animal occupies its own ecological *niche*.", m:"（生態系での）居場所・役割", kana:"ニッチ", cat:"nat", lv:3, note:"Grinnellの用語", d:["群れ","縄張りの境界","繁殖地"]},
 {s:"The grizzly bear was *extirpated* from the park long ago.", m:"（その地域で）絶滅した", kana:"エクスターペイテッド", cat:"nat", lv:3, note:"NPS:局地的絶滅", d:["再導入された","保護された","急増した"]},
 {s:"Introduced trout are a *non-native* species here.", m:"外来の・在来でない", kana:"ノンネイティブ", cat:"nat", lv:2, d:["絶滅危惧の","固有の","夜行性の"]},
 {s:"*Invasive* plants crowd out native wildflowers.", m:"侵入して広がる・侵略的な", kana:"インベイシブ", cat:"nat", lv:3, d:["在来の","希少な","栽培された"]},
 {s:"Several frogs here are now *endangered*.", m:"絶滅の危機にある", kana:"エンデンジャード", cat:"nat", lv:2, d:["繁栄している","外来の","保護された"]},
 {s:"Alpine plants *adapt* to cold, harsh conditions.", m:"適応する", kana:"アダプト", cat:"nat", lv:2, d:["枯死する","移動する","群生する"]},
 {s:"Wildflowers *thrive* in the damp spring meadow.", m:"生い茂る・繁栄する", kana:"スライブ", cat:"nat", lv:2, d:["枯れる","休眠する","散る"]},
 {s:"Bears *roam* widely in search of food.", m:"歩き回る・徘徊する", kana:"ローム", cat:"nat", lv:2, d:["身を潜める","縄張りを守る","巣にこもる"]},
 {s:"Lizards *bask* on warm granite in the sun.", m:"日なたぼっこをする", kana:"バスク", cat:"nat", lv:3, d:["身を隠す","餌をあさる","水を浴びる"]},
 {s:"A pair of birds build a *nest* on the ledge.", m:"巣", kana:"ネスト", cat:"nat", lv:1, d:["ねぐら","縄張り","えさ場"]},
 {s:"The mountain lion is *elusive* and hard to spot.", m:"とらえどころのない・見つけにくい", kana:"イルーシブ", cat:"nat", lv:3, d:["どう猛な","人になれた","群れる"]},
 {s:"Native meadows are surprisingly *resilient* after fire.", m:"回復力のある", kana:"リジリエント", cat:"nat", lv:3, d:["もろい","変化しない","乾ききった"]},
 {s:"In winter the meadow plants lie *dormant*.", m:"休眠中の", kana:"ドーマント", cat:"nat", lv:3, d:["満開の","枯死した","結実した"]},
 {s:"Managers use *prescribed* fire to renew the forest.", m:"（計画的に）管理された・処方された", kana:"プリスクライブド", cat:"nat", lv:3, note:"prescribed fire=計画的火入れ", d:["偶発的な","禁じられた","自然発生の"]},
 {s:"Crews reduce fuel by *thinning* dense stands of trees.", m:"間引き・間伐（すること）", kana:"シニング", cat:"nat", lv:3, d:["植林","伐採の全面禁止","接ぎ木"]},
 {s:"Restoring a natural fire *regime* keeps forests healthy.", m:"（一定の）体制・様式", kana:"レジーム", cat:"nat", lv:3, note:"fire regime=火災体制", d:["周期表","保護区域","禁止令"]},
 {s:"The meadow is *teeming* with insects and birds.", m:"（生き物が）あふれている", kana:"ティーミング", cat:"nat", lv:3, d:["静まり返った","干上がった","荒れ果てた"]},
 {s:"Acorns were a *staple* food for the Ahwahneechee.", m:"主食・中心となる食料", kana:"ステープル", cat:"nat", lv:2, d:["珍味","保存食","調味料"]},

/* ===================== 滝（placestogo: Waterfalls 主体） ===================== */
 {s:"By August, Yosemite Falls is often only a *trickle*.", m:"細い流れ・ちょろちょろ", kana:"トリクル", cat:"spot", lv:2, note:"NPS:夏は涸れがち", d:["激流","水たまり","渦"]},
 {s:"Peak *runoff* usually happens in May or June.", m:"（雪解けなどの）流出水", kana:"ランオフ", cat:"spot", lv:2, note:"peak runoff=最大流量期", d:["蒸発量","降雪量","地下水位"]},
 {s:"Waterfalls swell as the *snowmelt* rushes down.", m:"雪解け（水）", kana:"スノーメルト", cat:"spot", lv:2, d:["夕立","湧き水","増水した泥"]},
 {s:"Autumn storms *rejuvenate* some of the falls.", m:"よみがえらせる・生き返らせる", kana:"リジュヴィネイト", cat:"spot", lv:3, note:"rejuvenate=再生させる", d:["涸らす","濁らせる","凍らせる"]},
 {s:"At high flow you hear the *booming* water from afar.", m:"どっと鳴り響く・とどろく", kana:"ブーミング", cat:"spot", lv:2, d:["かすかな","澄んだ","途切れがちな"]},
 {s:"Stay on the trail—the granite is dangerously *slick*.", m:"つるつる滑る", kana:"スリック", cat:"spot", lv:2, note:"NPS安全注意", d:["ざらざらの","乾いた","平らな"]},
 {s:"The river's *current* is very powerful near the falls.", m:"（水の）流れ・水流", kana:"カレント", cat:"spot", lv:1, d:["水位","水温","川幅"]},
 {s:"Creeks *tumble* down the slopes as short cascades.", m:"転げるように流れ落ちる", kana:"タンブル", cat:"spot", lv:2, d:["湧き上がる","よどむ","逆流する"]},
 {s:"Yosemite Falls drops in three separate *tiers*.", m:"段・層", kana:"ティアーズ", cat:"spot", lv:2, note:"上・中・下段の三段", d:["支流","滝つぼ","うねり"]},
 {s:"At sunset Horsetail Fall seems to be *ablaze*.", m:"燃え立つような", kana:"アブレイズ", cat:"spot", lv:3, note:"2月のfirefall現象", d:["凍りついた","かすんだ","荒れ狂う"]},
 {s:"The falling water can *glow* orange in the evening light.", m:"ほのかに輝く", kana:"グロー", cat:"spot", lv:1, d:["ざわめく","渦巻く","はじける"]},
 {s:"Ribbon Fall shows a thin, *wispy* stream of water.", m:"か細くかすんだ", kana:"ウィスピー", cat:"spot", lv:3, d:["ごうごうと厚い","にごった","段状の"]},
 {s:"Bridalveil Fall has a light, *swaying* flow.", m:"揺れ動く", kana:"スウェイング", cat:"spot", lv:2, d:["まっすぐ落ちる","渦巻く","凍った"]},
 {s:"Bridalveil drifts like a thin *veil* of water.", m:"薄い覆い・とばり", kana:"ヴェイル", cat:"spot", lv:2, d:["柱","渦","飛沫の帯"]},
 {s:"The water seems to *plummet* straight off the cliff.", m:"真っ逆さまに落ちる", kana:"プラメット", cat:"spot", lv:3, note:"plummet=急降下", d:["せり上がる","にじみ出る","跳ね返る"]},
 {s:"Hikers gather at the *brink* of the fall.", m:"（滝などの）ふち・きわ", kana:"ブリンク", cat:"spot", lv:3, d:["滝つぼ","中ほど","水源"]},
 {s:"Many falls are *seasonal*, flowing only in spring.", m:"季節限定の・季節による", kana:"シーズナル", cat:"spot", lv:2, d:["常に一定の","人工の","地下の"]},
 {s:"A few falls are *perennial*, flowing all year.", m:"一年中絶えない", kana:"ペレニアル", cat:"spot", lv:3, note:"perennial=通年の", d:["季節限定の","短命の","干上がった"]},
 {s:"Some cascades are *ephemeral*, gone within days.", m:"つかの間の・はかない", kana:"エフェメラル", cat:"spot", lv:3, d:["永続的な","巨大な","規則的な"]},
 {s:"After the storm the creek became a raging *torrent*.", m:"激流・奔流", kana:"トレント", cat:"spot", lv:3, d:["よどみ","細流","水たまり"]},
 {s:"Meltwater *gushes* from the cliff in late spring.", m:"どっと噴き出す", kana:"ガッシュ", cat:"spot", lv:2, d:["したたる","引いていく","凍りつく"]},
 {s:"The mist can *drench* hikers on the Mist Trail.", m:"びしょ濡れにする", kana:"ドレンチ", cat:"spot", lv:2, d:["乾かす","冷やす","かすませる"]},
 {s:"Spray from Vernal Fall will *soak* your clothes.", m:"ずぶ濡れにする・浸す", kana:"ソーク", cat:"spot", lv:1, d:["温める","はじく","乾かす"]},
 {s:"White, *frothy* water churns below the fall.", m:"泡立った", kana:"フロシー", cat:"spot", lv:3, d:["澄んだ","よどんだ","凍った"]},
 {s:"The Merced *churns* among the boulders below Vernal Fall.", m:"激しく渦巻く・かき回す", kana:"チャーン", cat:"spot", lv:2, d:["静かに流れる","しみ出す","干上がる"]},
 {s:"A deep *plunge pool* forms at the base of the fall.", m:"滝つぼ", kana:"プランジプール", cat:"geo", lv:2, d:["源流","三日月湖","貯水池"]},
 {s:"A sudden *downpour* can swell the creeks fast.", m:"どしゃ降り", kana:"ダウンポア", cat:"spot", lv:2, d:["霧雨","日照り","そよ風"]},
 {s:"Spring snowmelt *replenishes* the rivers.", m:"（減った分を）満たし直す・補給する", kana:"リプレニッシュ", cat:"spot", lv:3, d:["せき止める","汚す","干上がらせる"]},
 {s:"In winter an *ice cone* builds at the base of the fall.", m:"氷の円錐（積もった氷の山）", kana:"アイスコーン", cat:"spot", lv:2, note:"NPS:冬のYosemite Falls", d:["氷の橋","つらら","流氷"]},
 {s:"Frost *accumulates* along the falls on winter nights.", m:"積もる・たまっていく", kana:"アキュミュレイツ", cat:"nat", lv:2, d:["溶け出す","飛び散る","乾く"]},
 {s:"Horsetail Fall *reflects* the orange glow of sunset.", m:"（光を）映し返す・反射する", kana:"リフレクツ", cat:"spot", lv:1, d:["さえぎる","吸い込む","散らす"]},
 {s:"Chilnualna Falls *hides* behind twists in the rock.", m:"見えないように隠れている", kana:"ハイズ", cat:"spot", lv:1, d:["そびえる","あふれ出る","崩れる"]},

/* ===================== 岩の名所（placestogo: Rock Formations 主体） ===================== */
 {s:"El Capitan *looms* over the western end of the valley.", m:"（ぬっと）そびえ立つ", kana:"ルームズ", cat:"geo", lv:2, note:"loom=不気味に迫る", d:["崩れ落ちる","くぼむ","遠ざかる"]},
 {s:"Half Dome is the most *recognized* symbol of Yosemite.", m:"よく知られた・見分けのつく", kana:"レコグナイズド", cat:"geo", lv:2, d:["忘れられた","隠れた","ありふれた"]},
 {s:"Half Dome is one of the most *sought-after* landmarks.", m:"人気の・皆が目指す", kana:"ソートアフター", cat:"geo", lv:3, note:"sought-after=引く手あまた", d:["立ち入り禁止の","知られざる","近づきやすい"]},
 {s:"Sentinel Rock stands like a *sentinel* over the valley.", m:"見張り番・番人", kana:"センティネル", cat:"geo", lv:3, note:"sentinel=歩哨", d:["王座","門","道しるべ"]},
 {s:"Snow clings to the Glacier Point *apron*.", m:"（崖の）裾状の斜面", kana:"エプロン", cat:"geo", lv:3, d:["頂の平地","尖った峰","深い割れ目"]},
 {s:"At dusk *alpenglow* turns the granite pink.", m:"（山肌の）夕映え・朝焼けの赤み", kana:"アルペングロー", cat:"geo", lv:3, note:"alpenglow=山の残照", d:["朝もや","稲妻","逆光の影"]},
 {s:"Half Dome is a *prominent* peak seen from Olmsted Point.", m:"目立つ・突き出た", kana:"プロミネント", cat:"geo", lv:2, d:["目立たない","低くなだらかな","隠れた"]},
 {s:"The Three Brothers look *stacked* atop each other.", m:"積み重なった", kana:"スタックト", cat:"geo", lv:2, d:["横並びの","散らばった","傾いた"]},
 {s:"Cathedral Rocks sit *opposite* El Capitan.", m:"向かい側の・反対側の", kana:"オポジット", cat:"geo", lv:1, d:["隣り合った","背後の","真下の"]},
 {s:"Visitors gaze up to feel the *enormity* of the cliffs.", m:"（圧倒的な）巨大さ", kana:"イノーミティ", cat:"geo", lv:3, d:["静けさ","古さ","もろさ"]},
 {s:"Over *eons*, rivers and ice carved the valley.", m:"悠久の時・非常に長い年月", kana:"イーオンズ", cat:"geo", lv:3, note:"eon=永遠に近い時間", d:["一瞬","一世代","数十年"]},
 {s:"Visitors *gaze* up at the towering granite walls.", m:"じっと見上げる・見つめる", kana:"ゲイズ", cat:"spot", lv:2, d:["駆け上がる","よじ登る","通り過ぎる"]},
 {s:"Glacier Point offers a fresh *perspective* from above.", m:"見る視点・眺めの角度", kana:"パースペクティブ", cat:"spot", lv:2, d:["休憩所","高度計","入口"]},
 {s:"El Capitan is a *formidable* wall for climbers.", m:"手ごわい・圧倒される", kana:"フォーミダブル", cat:"geo", lv:3, d:["ささやかな","なだらかな","崩れやすい"]},
 {s:"The granite face is truly *imposing*.", m:"堂々とした・威圧的な", kana:"インポージング", cat:"geo", lv:3, d:["こぢんまりした","素朴な","色あせた"]},
 {s:"A rocky *crag* juts out above the trail.", m:"ごつごつした岩山・険しい岩", kana:"クラッグ", cat:"geo", lv:3, d:["草地","砂州","岩棚"]},
 {s:"A rocky *promontory* juts out over the canyon.", m:"突き出た高台・岬状の張り出し", kana:"プロモントリー", cat:"geo", lv:3, d:["くぼ地","谷底","分岐点"]},
 {s:"The trail crosses a low *col* between two peaks.", m:"鞍部（尾根の低いくびれ）", kana:"コル", cat:"geo", lv:3, d:["頂上","谷口","岩の裂け目"]},
 {s:"A rounded granite *knob* rises from the meadow.", m:"丸いこぶ状の岩", kana:"ノブ", cat:"geo", lv:2, d:["尖塔","裂け目","くぼみ"]},
 {s:"The peak's steep *flank* catches the morning sun.", m:"（山の）側面・斜面", kana:"フランク", cat:"geo", lv:2, d:["頂上","裾野","尾根筋"]},
 {s:"Half Dome's sharp *profile* stands against the sky.", m:"輪郭・横から見た形", kana:"プロファイル", cat:"geo", lv:2, d:["影","高さ","裾"]},
 {s:"At dusk the peaks become dark *silhouettes*.", m:"影絵・黒い輪郭", kana:"シルエッツ", cat:"geo", lv:2, d:["残照","霧の帯","雪形"]},
 {s:"The whole *massif* glows at sunrise.", m:"山塊（ひとかたまりの山）", kana:"マシーフ", cat:"geo", lv:3, d:["尾根道","谷筋","裾野"]},
 {s:"A natural granite *buttress* braces the cliff.", m:"支え壁のように張り出した岩", kana:"バットレス", cat:"geo", lv:3, d:["割れ目","くぼみ","岩棚"]},
 {s:"Half Dome is a *monumental* block of granite.", m:"記念碑のように巨大な", kana:"モニュメンタル", cat:"geo", lv:3, d:["ささやかな","もろい","平凡な"]},
 {s:"Mirror Lake sits directly *beneath* Half Dome.", m:"〜の真下に", kana:"ビニース", cat:"geo", lv:1, d:["〜のかなたに","〜に沿って","〜を越えて"]},
 {s:"Cathedral Spires *rise* sharply beside the creek.", m:"（すっと）立ち上がる・そびえる", kana:"ライズ", cat:"geo", lv:1, d:["崩れる","沈む","広がる"]},
 {s:"Half Dome *towers* nearly 5,000 feet above the floor.", m:"はるか高くそびえる", kana:"タワーズ", cat:"geo", lv:2, note:"NPS:谷底から約5,000ft", d:["張り出す","くぼむ","傾く"]},

/* ===================== 展望地（placestogo: Viewpoints 主体） ===================== */
 {s:"Glacier Point gives a *commanding* view of the valley.", m:"見晴らしのきく・見下ろす", kana:"コマンディング", cat:"spot", lv:3, note:"commanding view", d:["さえぎられた","ぼやけた","限られた"]},
 {s:"The view from Glacier Point is truly *spectacular*.", m:"壮観な・目を見張る", kana:"スペクタキュラー", cat:"spot", lv:2, d:["平凡な","陰気な","こぢんまりした"]},
 {s:"Pull into a *turnout* whenever a view opens up.", m:"路肩の待避スペース", kana:"ターンアウト", cat:"spot", lv:2, note:"NPS:展望の待避所", d:["登山口","検問所","休憩小屋"]},
 {s:"From the road you catch a *glimpse* of Half Dome.", m:"ちらりと見えること・一瞥", kana:"グリンプス", cat:"spot", lv:2, d:["全景","接写","逆光"]},
 {s:"Half Dome forms the *backdrop* to the valley.", m:"背景", kana:"バックドロップ", cat:"spot", lv:2, d:["前景","縁取り","中心"]},
 {s:"Indian paintbrush colors the *foreground* of the scene.", m:"前景・手前", kana:"フォアグラウンド", cat:"spot", lv:3, d:["背景","遠景","額縁"]},
 {s:"The jagged *skyline* cuts against the evening sky.", m:"空を背にした稜線・輪郭", kana:"スカイライン", cat:"spot", lv:2, d:["水平線","谷底","雲海"]},
 {s:"Distant peaks line the far *horizon*.", m:"地平線・水平線", kana:"ホライズン", cat:"spot", lv:1, d:["尾根道","谷筋","近景"]},
 {s:"On a clear day *visibility* reaches the Coast Ranges.", m:"視界・見通し", kana:"ビジビリティ", cat:"spot", lv:2, note:"El Portal View", d:["標高","気温","日照時間"]},
 {s:"A summer *haze* can soften the distant view.", m:"かすみ・もや", kana:"ヘイズ", cat:"spot", lv:2, d:["突風","西日","雨脚"]},
 {s:"After rain the air has wonderful *clarity*.", m:"澄み具合・くっきりした鮮明さ", kana:"クラリティ", cat:"spot", lv:3, d:["湿り気","暖かさ","静けさ"]},
 {s:"Olmsted Point shows the valley from a new *angle*.", m:"角度・見る向き", kana:"アングル", cat:"spot", lv:1, d:["高度","距離","面積"]},
 {s:"Clouds Rest is a *striking* peak from Olmsted Point.", m:"際立った・目を引く", kana:"ストライキング", cat:"spot", lv:2, d:["目立たない","崩れかけた","隠れた"]},
 {s:"Washburn Point sits just *south of* Glacier Point.", m:"〜の南に", kana:"サウスオブ", cat:"spot", lv:1, d:["〜の真上に","〜の内側に","〜の下流に"]},
 {s:"The Merced River *winds* through the canyon below.", m:"曲がりくねって進む", kana:"ワインズ", cat:"spot", lv:2, d:["まっすぐ流れる","せき止められる","干上がる"]},
 {s:"The Tuolumne River *meanders* across the meadow.", m:"（川が）蛇行する", kana:"ミアンダーズ", cat:"geo", lv:3, note:"meander=曲流する", d:["直進する","伏流する","逆流する"]},
 {s:"O'Shaughnessy Dam holds back a large *reservoir*.", m:"貯水池", kana:"レザヴォワール", cat:"spot", lv:2, note:"Hetch Hetchy", d:["三日月湖","干潟","用水路"]},
 {s:"The *dam* stores water at the west end of the valley.", m:"川をせき止める堤・ダム", kana:"ダム", cat:"spot", lv:1, d:["水門","桟橋","堤防道路"]},
 {s:"The dam *impounds* the Tuolumne River's water.", m:"せき止めてためる", kana:"インパウンズ", cat:"spot", lv:3, note:"impound=貯留する", d:["放流する","浄化する","分流する"]},
 {s:"Kolana Rock *rises* above the reservoir.", m:"（水面から）立ち上がる", kana:"ライジズ", cat:"spot", lv:1, d:["沈む","傾く","崩れる"]},
 {s:"Half Dome is *reflected* in the calm Merced River.", m:"（水面に）映し出される", kana:"リフレクテッド", cat:"spot", lv:2, note:"Sentinel Bridge", d:["ゆがめられる","かき消される","覆い隠される"]},
 {s:"Tunnel View is one of the most *famous* views in the park.", m:"有名な・名高い", kana:"フェイマス", cat:"spot", lv:1, d:["知られざる","立ち入れない","新しい"]},
 {s:"Some say Glacier Point is the most *stunning* spot.", m:"衝撃的なほど見事な", kana:"スタニング", cat:"spot", lv:2, d:["がっかりする","ありふれた","殺風景な"]},
 {s:"A *turnoff* leads to the quiet viewpoint.", m:"わき道への分岐", kana:"ターンオフ", cat:"spot", lv:2, d:["行き止まり","合流点","周回路"]},

/* ===================== 高地・トゥオルミ（placestogo: Tuolumne/Tioga 主体） ===================== */
 {s:"Tuolumne Meadows lies in Yosemite's *high country*.", m:"標高の高い山岳地帯", kana:"ハイカントリー", cat:"spot", lv:2, note:"NPS頻出", d:["低地の盆地","海辺の平野","谷底の森"]},
 {s:"The meadow is *graced* by the winding Tuolumne River.", m:"優美に引き立てられた", kana:"グレイスト", cat:"spot", lv:3, note:"graced by", d:["ふさがれた","荒らされた","分断された"]},
 {s:"A broad, *open* meadow spreads toward the peaks.", m:"開けた・さえぎるもののない", kana:"オープン", cat:"spot", lv:1, d:["うっそうとした","囲まれた","狭まった"]},
 {s:"Gentle, *rolling* terrain surrounds the river.", m:"なだらかに起伏する", kana:"ローリング", cat:"geo", lv:2, d:["切り立った","平坦な","入り組んだ"]},
 {s:"A vast *expanse* of granite stretches to the horizon.", m:"広がり・広大な区域", kana:"エクスパンス", cat:"geo", lv:2, d:["割れ目","くぼみ","裾野"]},
 {s:"The high country feels wild and *vast*.", m:"広大な", kana:"ヴァスト", cat:"spot", lv:2, d:["手狭な","険しい","にぎやかな"]},
 {s:"A *sprawling* meadow opens beyond the trees.", m:"広々と広がった", kana:"スプロウリング", cat:"spot", lv:3, d:["こぢんまりした","険しい","立ち入り禁止の"]},
 {s:"The trail crosses *undulating* granite slabs.", m:"波打つように起伏する", kana:"アンジュレイティング", cat:"geo", lv:3, d:["まっ平らな","切り立った","ぬかるんだ"]},
 {s:"Tioga Road climbs to a high mountain *pass*.", m:"峠・山越えの道", kana:"パス", cat:"spot", lv:2, d:["谷口","分水界","登山口"]},
 {s:"Pothole Dome offers a *sweeping* first view of the meadow.", m:"ぐるりと見渡す・広々とした", kana:"スイーピング", cat:"spot", lv:2, d:["ごく狭い","さえぎられた","真下を向いた"]},
 {s:"A small *tarn* sits in a hollow near the pass.", m:"（氷河が作った）山上の小さな湖", kana:"ターン", cat:"geo", lv:3, note:"tarn=圏谷湖", d:["湿原","滝つぼ","貯水池"]},
 {s:"These streams are the *headwaters* of the Merced.", m:"（川の）源流・水源地", kana:"ヘッドウォーターズ", cat:"geo", lv:3, d:["河口","中流","三角州"]},
 {s:"Lembert Dome marks the *east end* of the meadow.", m:"東のはずれ", kana:"イーストエンド", cat:"spot", lv:1, d:["中心部","入口","最高点"]},
 {s:"Winter snow *lingers* late into spring up high.", m:"いつまでも残る・居座る", kana:"リンガーズ", cat:"nat", lv:3, note:"linger=長引く", d:["すぐ消える","降り積もる","溶け流れる"]},
 {s:"The thin mountain air feels *crisp* and cool.", m:"ひんやり澄んだ", kana:"クリスプ", cat:"nat", lv:2, d:["蒸し暑い","よどんだ","生ぬるい"]},

/* ===================== 草原・湿地（placestogo: Meadows & Wetlands 主体） ===================== */
 {s:"Meadows and *wetlands* hold the park's richest life.", m:"湿地", kana:"ウェットランズ", cat:"nat", lv:2, note:"NPS:多様性が最も高い", d:["荒れ地","砂地","岩場"]},
 {s:"A soggy *marsh* borders the slow creek.", m:"沼地・湿原", kana:"マーシュ", cat:"nat", lv:2, d:["草原","裸地","砂丘"]},
 {s:"A spongy *bog* traps water among the mosses.", m:"泥炭質の湿地", kana:"ボグ", cat:"nat", lv:3, d:["乾いた台地","砂利の河原","岩の露頭"]},
 {s:"Water *seeps* slowly through the meadow soil.", m:"じわじわしみ出る", kana:"シープス", cat:"nat", lv:2, d:["噴き出す","跳ね返る","干上がる"]},
 {s:"After snowmelt the ground stays *saturated*.", m:"水をたっぷり含んだ", kana:"サチュレイテッド", cat:"nat", lv:3, note:"saturated=飽和した", d:["干からびた","凍った","踏み固められた"]},
 {s:"The meadow soil is soft and *damp*.", m:"湿った", kana:"ダンプ", cat:"nat", lv:1, d:["からからの","硬い","砂利質の"]},
 {s:"Wildflowers *bloom* across the meadow in June.", m:"咲く・開花する", kana:"ブルーム", cat:"nat", lv:1, d:["枯れる","芽を出す","実る"]},
 {s:"Dogwood *blossoms* brighten the spring forest.", m:"花・花が開くこと", kana:"ブロッサムズ", cat:"nat", lv:2, d:["若葉","木の実","落ち葉"]},
 {s:"Meadows are *fragile* and easily trampled.", m:"もろい・傷つきやすい", kana:"フラジャイル", cat:"nat", lv:2, note:"NPS:木道で保護", d:["丈夫な","乾いた","広大な"]},
 {s:"Bees are important *pollinators* in the meadow.", m:"花粉を運ぶ生き物", kana:"ポリネイターズ", cat:"nat", lv:3, d:["捕食者","分解者","害虫"]},
 {s:"Butterflies sip *nectar* from the wildflowers.", m:"花の蜜", kana:"ネクター", cat:"nat", lv:2, d:["花粉","樹液","露"]},
 {s:"*Riparian* plants line the riverbanks.", m:"川辺の・水辺の", kana:"リパリアン", cat:"nat", lv:3, note:"riparian=河畔の", d:["高山の","砂漠の","海辺の"]},
 {s:"The wet meadow looks *verdant* in early summer.", m:"青々とした・みずみずしい緑の", kana:"ヴァーダント", cat:"nat", lv:3, d:["枯れ色の","乾ききった","色あせた"]},
 {s:"Clumps of *sedge* grow in the marshy ground.", m:"スゲ（湿地に生える草）", kana:"セッジ", cat:"nat", lv:3, d:["針葉樹","つる草","低木のやぶ"]},
 {s:"Tall *reeds* sway at the water's edge.", m:"アシ・葦", kana:"リーズ", cat:"nat", lv:2, d:["シダ","苔","つる草"]},
 {s:"*Willows* grow thick along the riverbank.", m:"ヤナギ", kana:"ウィローズ", cat:"nat", lv:2, note:"NPS:河畔で植栽・復元", d:["カシ類","針葉樹","低木のやぶ"]},
 {s:"Quaking *aspen* leaves tremble in the breeze.", m:"葉が揺れる落葉樹（ヤマナラシ）", kana:"アスペン", cat:"nat", lv:3, d:["常緑の針葉樹","つる植物","湿地の草"]},
 {s:"A dense *thicket* hides small animals.", m:"やぶ・茂み", kana:"シケット", cat:"nat", lv:2, d:["草地","裸地","切り株"]},
 {s:"Meadow edges *teem* with birds and insects.", m:"（生き物で）あふれる", kana:"ティーム", cat:"nat", lv:3, d:["静まり返る","干上がる","荒れ果てる"]},
 {s:"Wet meadows support a great *variety* of life.", m:"多様さ・いろいろな種類", kana:"バラエティ", cat:"nat", lv:1, d:["希少さ","偏り","少なさ"]},

/* ===================== 巨木の森（placestogo: Mariposa Grove 主体） ===================== */
 {s:"Mariposa Grove has over 500 *mature* sequoias.", m:"十分に育った・成熟した", kana:"マチュア", cat:"nat", lv:2, note:"NPS:成木500本超", d:["枯れかけた","若い","移植された"]},
 {s:"Giant sequoias are *towering* trees.", m:"見上げるほど高い", kana:"タワリング", cat:"nat", lv:2, d:["ずんぐりした","低木の","つる性の"]},
 {s:"A giant sequoia has an enormous *girth*.", m:"幹回り・胴回り", kana:"ガース", cat:"nat", lv:3, note:"girth=周囲", d:["高さ","樹齢","枝ぶり"]},
 {s:"The tree's thick *trunk* is fire-scarred but alive.", m:"幹", kana:"トランク", cat:"nat", lv:1, d:["枝","根","樹冠"]},
 {s:"Sequoia bark is thick and *fire-resistant*.", m:"火に強い・耐火性の", kana:"ファイアレジスタント", cat:"nat", lv:3, note:"NPS:厚い樹皮", d:["燃えやすい","腐りやすい","水を通す"]},
 {s:"The bark has a warm, *cinnamon* color.", m:"赤みを帯びた褐色の", kana:"シナモン", cat:"nat", lv:2, d:["青みがかった","灰白色の","黒ずんだ"]},
 {s:"Sequoia bark feels soft and *fibrous*.", m:"繊維質の", kana:"ファイブラス", cat:"nat", lv:3, d:["つるつるした","もろく砕ける","樹脂質の"]},
 {s:"The largest tree is called the grove's *monarch*.", m:"抜きんでた大木・王者", kana:"モナーク", cat:"nat", lv:3, d:["若木","切り株","並木"]},
 {s:"These *ancient* trees are thousands of years old.", m:"太古の・非常に古い", kana:"エインシェント", cat:"nat", lv:2, d:["若々しい","移植された","枯れた"]},
 {s:"The grove holds many *venerable* old giants.", m:"由緒ある・古く尊い", kana:"ヴェネラブル", cat:"nat", lv:3, d:["若い","ありふれた","病んだ"]},
 {s:"A *gnarled* trunk twists toward the sky.", m:"ねじれてごつごつした", kana:"ナールド", cat:"nat", lv:3, d:["まっすぐな","なめらかな","細い"]},
 {s:"Fire left the base *charred* but the tree survived.", m:"黒焦げになった", kana:"チャード", cat:"nat", lv:3, d:["水浸しの","苔むした","白くなった"]},
 {s:"Fire helps sequoia seeds *sprout*.", m:"芽を出す・芽吹く", kana:"スプラウト", cat:"nat", lv:2, d:["枯れる","散る","実る"]},
 {s:"Tiny *seedlings* rise from the burned soil.", m:"苗・実生の若い芽", kana:"シードリングズ", cat:"nat", lv:2, d:["切り株","落ち葉","枯れ枝"]},
 {s:"A young *sapling* may take centuries to mature.", m:"若木・苗木", kana:"サプリング", cat:"nat", lv:2, d:["老木","切り株","倒木"]},
 {s:"Sunlight filters through the forest *shade*.", m:"日陰", kana:"シェイド", cat:"nat", lv:1, d:["下草","樹皮","梢"]},
 {s:"The Bachelor and Three Graces grow in a tight *cluster*.", m:"かたまり・群れ", kana:"クラスター", cat:"nat", lv:2, note:"Mariposa Groveの名木", d:["一列","散在","円陣"]},

/* ===================== 歴史的建物・ワウォナ（placestogo: Wawona/Historic） ===================== */
 {s:"Wawona is home to the *historic* Wawona Hotel.", m:"歴史的な・由緒ある", kana:"ヒストリック", cat:"spot", lv:1, d:["近代的な","仮設の","無名の"]},
 {s:"The old hotel has a charming, *rustic* style.", m:"素朴な・田舎風の", kana:"ラスティック", cat:"spot", lv:2, d:["豪華な","近未来的な","無機質な"]},
 {s:"Wawona offers *lodging* near the south entrance.", m:"宿泊施設", kana:"ロジング", cat:"spot", lv:2, d:["食堂","案内所","駐車場"]},
 {s:"Guests relax on the hotel's wide *veranda*.", m:"外に張り出した縁側・広い縁", kana:"ヴェランダ", cat:"spot", lv:2, d:["中庭","地下室","屋根裏"]},
 {s:"A rustic log *cabin* stands among the pines.", m:"丸太小屋・小さな家", kana:"キャビン", cat:"spot", lv:1, d:["天幕","納屋","望楼"]},
 {s:"The old buildings are carefully *preserved*.", m:"保存された", kana:"プリザーブド", cat:"spot", lv:2, d:["取り壊された","改築された","放棄された"]},
 {s:"The History Center *restored* several old structures.", m:"修復した・元通りにした", kana:"リストアド", cat:"spot", lv:2, d:["解体した","増築した","移設した"]},
 {s:"The center displays a full-size *replica* of a wagon.", m:"複製・再現物", kana:"レプリカ", cat:"spot", lv:2, d:["設計図","模型の破片","本物の遺品"]},
 {s:"The museum's *exhibits* explain Yosemite's story.", m:"展示（物）", kana:"エキシビッツ", cat:"spot", lv:2, note:"Yosemite Museum", d:["収蔵庫","入場券","案内係"]},
 {s:"The collection holds many Native American *artifacts*.", m:"（人が作った）遺物・工芸品", kana:"アーティファクツ", cat:"spot", lv:2, d:["化石","自然標本","複製画"]},
 {s:"The small *chapel* dates from the 1800s.", m:"礼拝堂", kana:"チャペル", cat:"spot", lv:1, note:"Yosemite Chapel", d:["集会所","鐘楼","宿坊"]},
 {s:"A pioneer *cemetery* lies near Yosemite Village.", m:"墓地", kana:"セメタリー", cat:"spot", lv:2, d:["庭園","広場","果樹園"]},
 {s:"A *covered bridge* crosses the river at Wawona.", m:"屋根のある橋", kana:"カバードブリッジ", cat:"spot", lv:2, d:["跳ね橋","石橋","吊り橋"]},
 {s:"An old *stable* once housed the hotel's horses.", m:"馬小屋・厩舎", kana:"ステイブル", cat:"spot", lv:2, d:["倉庫","鍛冶場","井戸小屋"]},

/* ===================== トレイル・安全（placestogo: Things to Do／安全注意） ===================== */
 {s:"The hike to Nevada Fall is *moderate* in difficulty.", m:"（難易度が）ほどほどの・中級の", kana:"モデレート", cat:"spot", lv:2, d:["非常に楽な","超上級の","危険極まる"]},
 {s:"The trail has a lot of *elevation gain*.", m:"登りで稼ぐ標高差", kana:"エレベーションゲイン", cat:"spot", lv:2, d:["水平距離","下り勾配","休憩回数"]},
 {s:"Mirror Lake is a two-mile *round-trip* walk.", m:"往復の", kana:"ラウンドトリップ", cat:"spot", lv:1, d:["片道の","周回の","一方通行の"]},
 {s:"This is an *out-and-back* trail to the viewpoint.", m:"同じ道を往復する（型の）", kana:"アウトアンドバック", cat:"spot", lv:3, d:["周回する","片道だけの","分岐の多い"]},
 {s:"The trail crosses a low *saddle* between peaks.", m:"鞍部・尾根のくぼみ", kana:"サドル", cat:"geo", lv:3, d:["頂上","谷口","岩棚"]},
 {s:"Hikers must *ford* the creek in early season.", m:"歩いて川を渡る", kana:"フォード", cat:"spot", lv:3, note:"ford=渡渉する", d:["飛び越える","迂回する","引き返す"]},
 {s:"The route *traverses* a steep granite slope.", m:"横切って進む・横断する", kana:"トラバース", cat:"spot", lv:3, d:["直登する","下って戻る","一周する"]},
 {s:"The last section requires a short *scramble*.", m:"手も使ってよじ登ること", kana:"スクランブル", cat:"spot", lv:3, d:["ゆるい下り","平坦な木道","渡渉"]},
 {s:"The ridge trail is narrow and *exposed*.", m:"（高所で）むき出しの・危険にさらされた", kana:"エクスポーズド", cat:"spot", lv:3, note:"exposed=切れ落ちた", d:["囲われた","日陰の","舗装された"]},
 {s:"Wear *sturdy* boots on the rocky trail.", m:"頑丈な", kana:"スタディ", cat:"spot", lv:2, d:["軽装の","使い捨ての","滑りやすい"]},
 {s:"Loose rock is a real *hazard* here.", m:"危険（要因）", kana:"ハザード", cat:"spot", lv:2, d:["名所","目印","近道"]},
 {s:"Signs urge *caution* near the waterfall's edge.", m:"用心・警戒", kana:"コーション", cat:"spot", lv:1, d:["静粛","歓迎","感謝"]},
 {s:"Please *heed* all posted warnings.", m:"（忠告に）従う・心に留める", kana:"ヒード", cat:"spot", lv:3, note:"heed=留意する", d:["無視する","掲示する","疑う"]},
 {s:"Bikers must *yield* to hikers on the path.", m:"道を譲る", kana:"イールド", cat:"spot", lv:2, d:["追い越す","先を急ぐ","並んで進む"]},
 {s:"Half Dome permits are limited by a daily *quota*.", m:"定員・割当", kana:"クオータ", cat:"spot", lv:3, d:["料金","抽選券","登録番号"]},
 {s:"Popular campgrounds require a *reservation*.", m:"予約", kana:"リザベーション", cat:"spot", lv:1, d:["身分証","会費","保証金"]},
 {s:"Some sites are *first-come*, first-served.", m:"先に来た順の", kana:"ファーストカム", cat:"spot", lv:2, d:["抽選制の","会員限定の","予約制の"]},
 {s:"A winter *closure* shuts the Glacier Point Road.", m:"（道路などの）閉鎖", kana:"クロージャー", cat:"spot", lv:2, d:["渋滞","工事","開通"]},
 {s:"Trails can be *slippery* after rain.", m:"滑りやすい", kana:"スリッパリー", cat:"spot", lv:1, d:["ぬかるんだ","急な","崩れた"]},
 {s:"A paved path makes the base *accessible* to all.", m:"行きやすい・利用しやすい", kana:"アクセシブル", cat:"spot", lv:2, note:"NPS:バリアフリー", d:["立ち入り禁止の","有料の","険しい"]},

/* ===================== 野生生物（Meadows/Wildlife 主体） ===================== */
 {s:"Meadows offer the best chance for *wildlife* viewing.", m:"野生生物", kana:"ワイルドライフ", cat:"nat", lv:1, d:["家畜","害虫","水草"]},
 {s:"Report any bear *sighting* to a ranger.", m:"目撃・見かけること", kana:"サイティング", cat:"nat", lv:2, d:["足跡","鳴き声","餌付け"]},
 {s:"Deer are *shy* and slip away when approached.", m:"用心深い・臆病な", kana:"シャイ", cat:"nat", lv:1, d:["攻撃的な","人なつこい","のろい"]},
 {s:"Small birds are *skittish* around people.", m:"おびえやすい・神経質な", kana:"スキティッシュ", cat:"nat", lv:3, d:["どう猛な","のんびりした","人になれた"]},
 {s:"Bears will *scavenge* food left at campsites.", m:"あさって食べる", kana:"スカヴェンジ", cat:"nat", lv:3, note:"NPS:食料管理注意", d:["狩りをする","貯め込む","分け与える"]},
 {s:"A coyote can act as a *scavenger*.", m:"腐肉などをあさる動物", kana:"スカヴェンジャー", cat:"nat", lv:3, d:["草食動物","捕食される側","群れの長"]},
 {s:"Squirrels are *diurnal*, active in daylight.", m:"昼行性の", kana:"ダイアーナル", cat:"nat", lv:3, d:["夜行性の","冬眠する","渡りをする"]},
 {s:"A bobcat's coat provides natural *camouflage*.", m:"保護色・見えにくくする擬態", kana:"カモフラージュ", cat:"nat", lv:2, d:["縄張り","警戒音","冬毛"]},
 {s:"Fawns *blend in* with the dappled forest floor.", m:"周囲に溶け込む", kana:"ブレンドイン", cat:"nat", lv:2, d:["目立って動く","群れをつくる","縄張りを守る"]},
 {s:"Male birds can be fiercely *territorial*.", m:"縄張り意識の強い", kana:"テリトリアル", cat:"nat", lv:3, d:["群れ好きの","渡り好きの","臆病な"]},
 {s:"Never feed bears; they become *habituated* to people.", m:"（人に）慣れてしまった", kana:"ハビチュエイテッド", cat:"nat", lv:3, note:"NPS重要", d:["おびえた","野生に戻った","冬眠中の"]},
 {s:"A *fledgling* owl waits on a low branch.", m:"巣立ち間近のひな", kana:"フレッジリング", cat:"nat", lv:3, d:["卵","老いた個体","親鳥"]},
 {s:"A peregrine falcon is a swift *raptor*.", m:"猛禽（タカ・ワシの類）", kana:"ラプター", cat:"nat", lv:3, d:["渡り鳥","水鳥","小鳥"]},
 {s:"The hawk grips its prey with sharp *talons*.", m:"（猛禽の）かぎ爪", kana:"タロンズ", cat:"nat", lv:3, d:["くちばし","羽根","足環"]},
 {s:"The jay's blue *plumage* is easy to spot.", m:"羽毛・羽の色", kana:"プルーメッジ", cat:"nat", lv:3, d:["鳴き声","巣","かぎ爪"]},
 {s:"Many birds here are *migratory*.", m:"渡りをする", kana:"マイグラトリー", cat:"nat", lv:2, d:["定住する","夜行性の","群れない"]},
 {s:"Trout *spawn* in the cold, clear streams.", m:"産卵する", kana:"スポーン", cat:"nat", lv:3, d:["回遊する","冬眠する","脱皮する"]},
 {s:"A mountain lion will *prowl* at dusk.", m:"（獲物を求め）うろつく", kana:"プロウル", cat:"nat", lv:3, d:["日なたで休む","群れで移動する","縄張りを鳴く"]},
 {s:"A bobcat *stalks* its prey through the brush.", m:"（獲物に）忍び寄る", kana:"ストーク", cat:"nat", lv:2, d:["追い散らす","呼び寄せる","見張る"]},
 {s:"A black bear *lumbers* across the meadow.", m:"のっそりと歩く", kana:"ランバーズ", cat:"nat", lv:3, d:["跳ねて進む","駆け抜ける","忍び寄る"]},
 {s:"Deer stay *wary* of predators.", m:"用心深い・警戒した", kana:"ウェアリー", cat:"nat", lv:2, d:["のんきな","人なつこい","攻撃的な"]},
 {s:"A marmot stays *alert* for danger.", m:"油断のない・警戒した", kana:"アラート", cat:"nat", lv:1, d:["眠たげな","無関心な","おとなしい"]},
 {s:"Pikas are small and surprisingly *agile*.", m:"動きが機敏な", kana:"アジャイル", cat:"nat", lv:2, d:["のろい","臆病な","大きい"]},
 {s:"A squirrel is *nimble* among the branches.", m:"すばしこい・身軽な", kana:"ニンブル", cat:"nat", lv:3, d:["どんくさい","慎重な","攻撃的な"]},
 {s:"A rattlesnake will *coil* when threatened.", m:"とぐろを巻く", kana:"コイル", cat:"nat", lv:2, d:["穴を掘る","毒を吐く","逃げ去る"]},
 {s:"Some animals *shed* their thick winter coat in spring.", m:"（毛や皮を）落とす・脱ぐ", kana:"シェッド", cat:"nat", lv:2, d:["蓄える","生やし直す","染め変える"]},
 {s:"Robins *hatch* their eggs in late spring.", m:"かえす・孵化させる", kana:"ハッチ", cat:"nat", lv:2, d:["抱え込む","巣立たせる","産みつける"]},
 {s:"Bears *rear* their cubs for over a year.", m:"（子を）育てる", kana:"リア", cat:"nat", lv:2, d:["見捨てる","引き離す","守り抜く"]},
 {s:"Coyotes may hunt together as a *pack*.", m:"（動物の）群れ", kana:"パック", cat:"nat", lv:2, d:["つがい","単独個体","縄張り"]},
 {s:"The mountain lion is a *solitary* hunter.", m:"単独でいる・群れない", kana:"ソリタリー", cat:"nat", lv:3, d:["群れをなす","渡りをする","昼行性の"]},
 {s:"Owls have remarkably *keen* hearing.", m:"（感覚が）鋭い", kana:"キーン", cat:"nat", lv:2, d:["鈍い","並みの","衰えた"]},
 {s:"Rangers identify animals by their tracks and *scat*.", m:"（動物の）ふん", kana:"スキャット", cat:"nat", lv:3, note:"scat=獣糞", d:["足跡","抜け毛","鳴き声"]},

/* ===================== 天候・季節（訪問の下調べ） ===================== */
 {s:"The sky turns gray and *overcast* before a storm.", m:"どんより曇った", kana:"オーバーキャスト", cat:"nat", lv:2, d:["澄みわたった","燃えるような","霧のない"]},
 {s:"A *brisk* wind sweeps across the high meadow.", m:"すがすがしく強い", kana:"ブリスク", cat:"nat", lv:2, d:["生ぬるい","よどんだ","かすかな"]},
 {s:"A sudden *gust* rattles the tent.", m:"突風", kana:"ガスト", cat:"nat", lv:2, d:["そよ風","雷鳴","にわか雨"]},
 {s:"A brief *squall* drops rain and wind together.", m:"突風を伴うにわか雨", kana:"スコール", cat:"nat", lv:3, d:["快晴","霧","日照り"]},
 {s:"A light *flurry* of snow drifts down.", m:"舞い散る雪", kana:"フラリー", cat:"nat", lv:2, d:["どしゃ降り","みぞれの塊","ひょう"]},
 {s:"A winter *blizzard* can close the roads.", m:"猛吹雪", kana:"ブリザード", cat:"nat", lv:2, d:["霧雨","砂嵐","雷雨"]},
 {s:"Valley summers can be hot but rarely *humid*.", m:"湿気の多い", kana:"ヒューミッド", cat:"nat", lv:2, d:["乾いた","肌寒い","穏やかな"]},
 {s:"The foothills are hot and *arid* in summer.", m:"乾燥した", kana:"アリッド", cat:"nat", lv:3, d:["じめじめした","涼しい","霧深い"]},
 {s:"By August the meadows look *parched*.", m:"からからに乾いた", kana:"パーチト", cat:"nat", lv:3, d:["水びたしの","青々とした","霜の降りた"]},
 {s:"Cold rain can turn to *sleet* up high.", m:"みぞれ", kana:"スリート", cat:"nat", lv:2, d:["霧","露","かすみ"]},
 {s:"A fine *drizzle* dampens the trail.", m:"霧雨", kana:"ドリズル", cat:"nat", lv:2, d:["豪雨","突風","雪解け"]},
 {s:"Autumn days are often *mild* and clear.", m:"穏やかな・温暖な", kana:"マイルド", cat:"nat", lv:1, d:["厳しい","蒸し暑い","荒れた"]},
 {s:"Winter above treeline is cold and *harsh*.", m:"厳しい・過酷な", kana:"ハーシュ", cat:"nat", lv:2, d:["穏やかな","湿った","快適な"]},
 {s:"At night the puddles *freeze* solid.", m:"凍る・凍りつく", kana:"フリーズ", cat:"nat", lv:1, d:["溶ける","あふれる","乾く"]},
 {s:"High passes stay *icy* well into spring.", m:"凍てついた・氷に覆われた", kana:"アイシー", cat:"nat", lv:2, d:["ぬかるんだ","乾いた","苔むした"]},
 {s:"The exposed ridge is *windswept* and bare.", m:"吹きさらしの", kana:"ウィンドスウェプト", cat:"geo", lv:3, d:["風の来ない","うっそうとした","湿った"]},
 {s:"Early mornings can feel quite *chilly*.", m:"肌寒い", kana:"チリー", cat:"nat", lv:1, d:["蒸し暑い","生ぬるい","うだるような"]},
 {s:"Heavy *snowfall* blankets the high country.", m:"降雪", kana:"スノーフォール", cat:"nat", lv:1, d:["落石","土砂降り","砂ぼこり"]},

/* ===================== 静寂・ヘッチヘッチ（placestogo: Hetch Hetchy 主体） ===================== */
 {s:"Hetch Hetchy sits in a *remote* northwest corner.", m:"遠く離れた・へんぴな", kana:"リモート", cat:"spot", lv:2, note:"NPS:静かな一角", d:["中心の","にぎやかな","行きやすい"]},
 {s:"Hetch Hetchy is a hidden *corner* of the park.", m:"一角・片隅", kana:"コーナー", cat:"spot", lv:1, d:["中心地","入口","頂上"]},
 {s:"This *hidden* valley is quiet in every season.", m:"人目につかない・隠れた", kana:"ヒドゥン", cat:"spot", lv:1, d:["有名な","開けた","混雑した"]},
 {s:"Locals call Hetch Hetchy a *treasure* worth visiting.", m:"宝・貴重なもの", kana:"トレジャー", cat:"spot", lv:1, d:["難所","秘密基地","立入禁止地"]},
 {s:"A dam *submerged* the floor of Hetch Hetchy Valley.", m:"水没させた・沈めた", kana:"サブマージド", cat:"hist", lv:3, d:["干上がらせた","埋め立てた","切り開いた"]},
 {s:"Snowmelt can *flood* low-lying meadows.", m:"氾濫させる・水浸しにする", kana:"フラッド", cat:"nat", lv:1, d:["乾かす","凍らせる","浄化する"]},
 {s:"An *aqueduct* carries the water to distant cities.", m:"導水路・水道", kana:"アクアダクト", cat:"hist", lv:3, note:"Hetch Hetchy水源", d:["発電所","貯水槽","用水池"]},
 {s:"The reservoir helps *supply* water to the region.", m:"供給する", kana:"サプライ", cat:"hist", lv:1, d:["浄化する","堰き止める","分配を断つ"]},
 {s:"Damming the valley was highly *controversial*.", m:"賛否の分かれる・物議をかもす", kana:"コントロバーシャル", cat:"hist", lv:3, d:["満場一致の","目立たない","一時的な"]},
 {s:"The valley feels calm and *peaceful*.", m:"静かで穏やかな", kana:"ピースフル", cat:"spot", lv:1, d:["騒がしい","荒れ果てた","混み合った"]},
 {s:"Visitors come here for the *serenity*.", m:"静けさ・安らぎ", kana:"セレニティ", cat:"spot", lv:2, d:["にぎわい","冒険","絶景"]},
 {s:"Backpackers seek the *solitude* of the wilderness.", m:"ひとりきりの静けさ", kana:"ソリチュード", cat:"spot", lv:3, d:["群衆","快適さ","交流"]},
 {s:"A hidden lake offers total *seclusion*.", m:"人里離れていること", kana:"セクルージョン", cat:"spot", lv:3, d:["利便性","にぎやかさ","開放感"]},
 {s:"The northwest corner stays *tranquil* year-round.", m:"穏やかで静かな", kana:"トランクィル", cat:"spot", lv:3, d:["騒然とした","荒れた","混雑した"]},
 {s:"Much of the park remains *untouched*.", m:"手つかずの", kana:"アンタッチト", cat:"spot", lv:2, d:["開発済みの","荒らされた","舗装された"]},
 {s:"The backcountry is largely *unspoiled*.", m:"荒らされていない・そこなわれていない", kana:"アンスポイルド", cat:"spot", lv:3, d:["汚染された","整備された","混雑した"]},
 {s:"The park is a *refuge* for many rare species.", m:"避難所・保護の場", kana:"レフュージ", cat:"nat", lv:2, d:["交易所","放牧地","展望所"]},
 {s:"Visitors are asked to *conserve* water and energy.", m:"（大切に）節約する・保全する", kana:"コンサーブ", cat:"spot", lv:2, d:["浪費する","独占する","汚す"]},
 {s:"Wildlife is *abundant* in the wet meadows.", m:"豊富な・ふんだんな", kana:"アバンダント", cat:"nat", lv:2, d:["乏しい","まばらな","消えつつある"]},
 {s:"Water grows *scarce* by late summer.", m:"乏しい・不足した", kana:"スケアス", cat:"nat", lv:2, d:["豊富な","濁った","冷たい"]},

/* ===================== 景観・体験（全域） ===================== */
 {s:"Visitors *stroll* along the valley loop at dusk.", m:"のんびり歩く・散策する", kana:"ストロール", cat:"spot", lv:2, d:["駆け抜ける","よじ登る","立ち止まる"]},
 {s:"It is easy to *wander* among the giant trees.", m:"あてもなく歩き回る", kana:"ワンダー", cat:"spot", lv:2, d:["急いで通る","道に迷って引き返す","一列で進む"]},
 {s:"Take time to *pause* and look around.", m:"立ち止まる・ひと息つく", kana:"ポーズ", cat:"spot", lv:1, d:["走り出す","引き返す","登り続ける"]},
 {s:"Visitors *marvel* at the sheer cliffs.", m:"驚嘆する・感嘆する", kana:"マーヴェル", cat:"spot", lv:2, d:["見落とす","不平を言う","恐れをなす"]},
 {s:"People come to *admire* Half Dome at sunset.", m:"見とれる・称賛する", kana:"アドマイア", cat:"spot", lv:1, d:["避ける","見張る","測る"]},
 {s:"Take a moment to *savor* the quiet.", m:"じっくり味わう", kana:"セイヴァー", cat:"spot", lv:3, d:["切り上げる","打ち破る","見過ごす"]},
 {s:"The scenery seems to *dwarf* every visitor.", m:"（比べて）小さく見せる", kana:"ドワーフ", cat:"spot", lv:3, note:"dwarf=見劣りさせる", d:["引き立てる","取り囲む","覆い隠す"]},
 {s:"Granite peaks *encircle* the meadow.", m:"取り囲む", kana:"エンサークル", cat:"geo", lv:2, d:["見下ろす","切り裂く","縁取る"]},
 {s:"The tunnel opening *frames* the valley view.", m:"（景色を）縁取る・額縁のように見せる", kana:"フレイムズ", cat:"spot", lv:2, note:"Tunnel View", d:["さえぎる","ゆがめる","照らす"]},
 {s:"The whole valley *unfolds* before you.", m:"目の前に広がる", kana:"アンフォールズ", cat:"spot", lv:2, d:["消えていく","閉じていく","遠ざかる"]},
 {s:"The high country *stretches* for miles.", m:"（遠くまで）広がる・伸びる", kana:"ストレッチズ", cat:"spot", lv:1, d:["途切れる","狭まる","盛り上がる"]},
 {s:"A stone bridge *spans* the Merced River.", m:"（川などに）差し渡す・またぐ", kana:"スパンズ", cat:"spot", lv:2, d:["せき止める","沿って走る","分ける"]},
 {s:"Half Dome *dominates* the eastern skyline.", m:"（景観を）圧して立つ・そびえ支配する", kana:"ドミネイツ", cat:"geo", lv:3, d:["溶け込む","見え隠れする","縁取る"]},
 {s:"Sequoias *dot* the hillside in scattered clumps.", m:"点在させる・ぽつぽつ散らばる", kana:"ドット", cat:"nat", lv:2, d:["密集させる","覆い尽くす","縁取る"]},
 {s:"Small lakes *scatter* across the high country.", m:"点在する・散らばる", kana:"スキャター", cat:"geo", lv:2, d:["集まる","連なる","干上がる"]},
 {s:"The lodge *nestles* among tall pines.", m:"（山あいに）抱かれるように位置する", kana:"ネッスルズ", cat:"spot", lv:3, d:["そびえ立つ","張り出す","孤立する"]},
 {s:"A hawk's nest *perches* high on the cliff.", m:"（高所に）ちょこんと位置する", kana:"パーチズ", cat:"nat", lv:2, d:["ぶら下がる","埋もれる","崩れ落ちる"]},
 {s:"The trail *hugs* the base of the cliff.", m:"（地形に）沿って進む", kana:"ハグズ", cat:"spot", lv:2, d:["横切る","急登する","遠ざかる"]},
 {s:"Snow *crowns* the highest peaks all winter.", m:"（頂を）覆い飾る・いただく", kana:"クラウンズ", cat:"geo", lv:2, d:["削り取る","溶かす","覆い隠す"]},
 {s:"Hikers walk along the canyon *rim*.", m:"へり・縁", kana:"リム", cat:"geo", lv:2, d:["谷底","中腹","裾野"]},
 {s:"You stand in the *midst* of towering granite.", m:"真っただ中", kana:"ミッドスト", cat:"spot", lv:2, d:["外れ","手前","はずれの縁"]},
 {s:"A lake sits *amid* the high peaks.", m:"〜の真ん中に", kana:"アミッド", cat:"spot", lv:2, d:["〜の外に","〜の下流に","〜の手前に"]},
 {s:"An *array* of peaks lines the horizon.", m:"ずらりと並んだ一群", kana:"アレイ", cat:"geo", lv:2, d:["ひとつの塊","わずかな数","切れ目"]},
 {s:"The meadow is a *tapestry* of colorful flowers.", m:"（多彩に）織りなす光景", kana:"タペストリー", cat:"nat", lv:3, d:["一面の枯れ野","むき出しの土","単調な緑"]},

/* ===================== クレーンフラット・タカ峠・タカ湖ほか（placestogo 各所） ===================== */
 {s:"Crane Flat is a *pleasant* forest and meadow area.", m:"心地よい・快適な", kana:"プレザント", cat:"spot", lv:1, note:"NPS:谷から約16マイル", d:["殺風景な","険しい","蒸し暑い"]},
 {s:"Wildflowers *carpet* the Crane Flat meadow in summer.", m:"一面を覆う", kana:"カーペット", cat:"nat", lv:2, d:["点在する","枯らす","縁取る"]},
 {s:"Colorful *wildflowers* bloom across the meadow.", m:"野の花・野生の草花", kana:"ワイルドフラワーズ", cat:"nat", lv:1, d:["雑草の茂み","苔","低木"]},
 {s:"Badger Pass has gentle, *groomed* ski slopes.", m:"（雪面が）整備された", kana:"グルームド", cat:"spot", lv:2, note:"Badger Passスキー場", d:["荒れた","急な","凍てついた"]},
 {s:"Tenaya Lake's surface can *shimmer* in the sun.", m:"きらめく・ゆらめき光る", kana:"シマー", cat:"spot", lv:2, d:["波立つ","濁る","凍る"]},
 {s:"On calm days the lake is *glassy* and still.", m:"鏡のように滑らかな", kana:"グラッシー", cat:"spot", lv:2, d:["波打つ","にごった","荒れた"]},
 {s:"The *placid* lake mirrors the surrounding peaks.", m:"波立たず穏やかな", kana:"プラシッド", cat:"spot", lv:3, d:["荒れ狂う","濁った","渦巻く"]},
 {s:"Olmsted Point is *strewn* with glacial boulders.", m:"ばらまかれ散らばった", kana:"ストルーン", cat:"geo", lv:3, note:"迷子石が点在", d:["きれいに掃かれた","積み上げられた","埋められた"]},
 {s:"Crane Flat is a quiet, *forested* area.", m:"森に覆われた", kana:"フォレステッド", cat:"nat", lv:1, d:["裸地の","岩がちの","水浸しの"]},
 {s:"A free *shuttle* loops around Yosemite Valley.", m:"園内を巡る送迎バス", kana:"シャトル", cat:"spot", lv:2, d:["有料の観光列車","貸し自転車","遊覧船"]},
 {s:"Summer *congestion* can fill the valley's roads.", m:"混雑・渋滞", kana:"コンジェスチョン", cat:"spot", lv:2, d:["閉鎖","静けさ","工事"]},
 {s:"The mountain road climbs in tight *hairpin* turns.", m:"急な折り返しの（カーブ）", kana:"ヘアピン", cat:"spot", lv:3, d:["ゆるやかな直線の","下り一方の","広い環状の"]},
 {s:"Pothole Dome is named for the *potholes* worn into its rock.", m:"（水が岩を削った）丸い穴", kana:"ポットホールズ", cat:"geo", lv:3, note:"甌穴（おうけつ）", d:["尖った峰","積み石","割れ目"]}
];
